---
title: "Analysis - all metazoans - COI"
author: "Emil Ellegaard Thomassen"
date: "`r Sys.Date()"
output: github_document
editor_options: 
  chunk_output_type: console
---
The following script performs plots of species richness, read distributions and community compositions of all metazoan reads of the COI data.

# Setup

Setup R and load packages

```{r Setup}
knitr::opts_chunk$set(
	echo = TRUE,
	fig.height = 5.5,
	message = FALSE,
	warning = FALSE,
	autodep = TRUE,
	cache = TRUE,
	cache.lazy = FALSE,
	tidy = TRUE,
	tidy.opts = list(width.cutoff = 80)
)
rm(list=ls())
gc()
Dir.Base <- here::here()



# Installing packages as needed
install.load.package <- function(x) {
  if (!require(x, character.only = TRUE))
    install.packages(x, repos='http://cran.us.r-project.org', dependencies = TRUE)
  require(x, character.only = TRUE)
}
package_vec <- c("kableExtra", "tidyverse","png", "jpeg", "sp", "ncf","rgdal","MASS", "raster", "ggmap", "ggplot2", "BiodiversityR", "pheatmap", "knitr", "printr", "ade4", "vegan", "ROBITools", "ROBITaxonomy", "dplyr", "tidyr", "plotrix")
sapply(package_vec, install.load.package)

knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, cache = TRUE, cache.lazy=FALSE, tidy.opts=list(width.cutoff=80),tidy=TRUE, fig.height=5.5)
options(digits=4, width = 90)

```

# All metazoans

First, for all metazoan ASVs

```{r Generating input df and create genera list with reads}

dataset<-readRDS("COI/Local_analysis/output/RDS_files/dataset_final")


#Generating input df


#Create temporary df with read counts in each sample from metabarcoding file
df_tmp<-data.frame(dataset@reads)
colnames(df_tmp)<-dataset@motus$final.otu



#Create temporary df to build file with the columns (sample, species, count, totalreads, freq)
df<-data.frame("sample"=c(), "species"=c(),"count"=c())
df<-rbind(df, c(1,1,1))
colnames(df)<-c("sample", "species", "count")


#Add row to the dataframe for each sample/species combination
for (i in 1:nrow(df_tmp)) {
  for (j in 1:ncol(df_tmp)) {
   if (df_tmp[i,j]!=0) 
     {df<-rbind(df, c(row.names(df_tmp)[i],colnames(df_tmp)[j],df_tmp[i,j]))
     } 
  }
}

#Subtract the first row which was only used to keep correct format
df<-df[-1,]

#Change type of columns (sample=factor, count=numeric)
df2<-data.frame("sample"=as.factor(df$sample), "species"=df$species, "count"=as.numeric(df$count))

#Calculate total reads in each sample
#Create df with unique sample names and totalreads vector
totalreads1<-data.frame("sample"=as.factor(unique(df2$sample)))
totalreads<-c()

#Add value for total reads in each sample to the sample_count vector
for (sample in unique(df2$sample)) {
  x1<-which(df2$sample==sample)
  x2<-sum(df2$count[x1[1]:x1[length(x1)]])
  totalreads<-append(totalreads, rep(x2, each=length(x1))) #Each total count added as many times as each sample in represented in df2
}

#Add totalreads to df2
df2<-cbind(df2,totalreads)


#Calculate frequency of each species in the sample
freq<-c()

for (i in 1:nrow(df2)) {
  x<-df2$count[i]/df2$totalreads[i]
  freq<-append(freq,x)
  
  
}


#Add to df2
df2<-cbind(df2, freq)

#Save as RDS

saveRDS(df2, file="COI/Local_analysis/output/RDS_files/df_for_plots_and_analysis_all")



#Generate df with ID and reads

dataset<-readRDS("COI/Local_analysis/output/RDS_files/dataset_final")

reads<-as.data.frame(dataset@reads)

reads<-t(reads)
otu<-as.character(dataset@motus$final.otu)
kingdom<-as.character(dataset@motus$kingdom_name)
phylum<-as.character(dataset@motus$phylum_name)
class<-as.character(dataset@motus$class_name)
order<-as.character(dataset@motus$order_name)
family<-as.character(dataset@motus$family_name)
genus<-as.character(dataset@motus$genus_name)
species<-as.character(dataset@motus$species_name)
dung<-as.character(dataset@motus$dung.associated)
type<-as.character(dataset@motus$type)
row.names(reads)<-otu

total<-rowSums(reads)

df<-as.data.frame(cbind(reads,total))
df<-as.data.frame(cbind(df,kingdom,phylum,class,order,family,genus))
df<-df[order(df$total, decreasing=TRUE),]

#Save as RDS

saveRDS(df, file="COI/Local_analysis/output/RDS_files/df_species_reads_all")

df_t<-t(df)
df_t<-df_t[-c(length(row.names(df_t))-:length(row.names(df_t))),]


#Export list
write.csv2(df,"COI/Local_analysis/output/tables/MOLS2020_COI_all_ASVs_with_reads.csv", row.names=TRUE)



#Aggregate on genera
df_genera<-aggregate(. ~ genus, data=df[,c(1:140)], FUN=sum)


saveRDS(df_genera, file="COI/Local_analysis/output/RDS_files/df_genera_reads_all")

#Aggregate on family
df_family<-aggregate(. ~ family, data=df[,c(1:140)], FUN=sum)


saveRDS(df_family, file="COI/Local_analysis/output/RDS_files/df_family_reads_all")



```

```{r Taxon list for each sample}

no.rare<-readRDS("COI/Local_analysis/output/RDS_files/dataset_after_aggregation")

  #List of species for each sample
sample_data <- as_tibble(no.rare@reads, rownames = "Sample")

longer_sample_data <- sample_data %>% 
  pivot_longer(cols = -Sample, names_to = "qseqid", values_to = "Reads")

species_data <- as_tibble(no.rare@motus, rownames = "qseqid", .name_repair = "universal") %>%
  dplyr::select(scientific_name, qseqid) ################# was species_name

combined_sample_species <- full_join(longer_sample_data, species_data) %>% 
  filter(Reads > 0) %>% 
  mutate(scientific_name = as.character(scientific_name)) %>% ################# was species_name
  arrange(Sample, qseqid, Reads) 

combined_sample_species %>% 
  group_by(Sample) %>% 
  mutate(ID = row_number()) %>% 
  dplyr::select(Sample, scientific_name, ID) %>% ################# was species_name
  pivot_wider(id_cols = ID, names_from = Sample, values_from = scientific_name) %>% ################# was species_name
  readr::write_csv2("COI/Local_analysis/output/tables/MOLS2020_COI_metazoa_taxon_list.csv", na = "")


```


```{r Richness plot and stacked barplot ASVs/species}

#Plotting the richness of sampling time as well as stacked barplot of all sampling times


#Loading libraries
library(tidyverse)
library(ROBITools)
library(ROBITaxonomy)
library(ggpubr)
library(dplyr)
library(ggplot2)
library(ggsci)
library(RColorBrewer)

#Set level order for plots
level_order <- c("January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December") 

#Load data
df_raw <- readRDS("COI/Local_analysis/output/RDS_files/df_for_plots_and_analysis_all")

dataset<-readRDS("COI/Local_analysis/output/RDS_files/dataset_final")

test<-df_raw[1:20,]


#Remove unidentified genera from list for richness calculations

idx_remove<-c()
idx_keep<-c()
for (i in 1:nrow(df_raw)) {
  ifelse(grepl("sp.",df_raw$species[i], fixed=TRUE), ifelse(grepl("\\(",df_raw$species[i]),idx_keep<-append(idx_keep,i),idx_remove<-append(idx_remove,i)),idx_keep<-append(idx_keep,i))
}


df_raw2<-df_raw[-idx_remove,]




Samples<-unique(df_raw2$sample)
Richness<-list()

for (i in 1:length(Samples)){
  df<-as.data.frame(Samples[i])
  colnames(df)<-c("Samples")
  Count<-sum(df_raw2$count[df_raw2$sample==Samples[i]] !=0)
  df<-cbind(df, Count)
  Richness<-rbind(Richness, df)
}

Richness<-Richness %>%
  dplyr::mutate(Samples=factor(Samples))  




#Mean richness pr. month - Galloway

Richness<-cbind(Richness, "source"=dataset@samples$source, "month"=dataset@samples$month, "habitat"=dataset@samples$habitat, "lat"=dataset@samples$lat, "lon"=dataset@samples$lon)

Richness<-Richness[order(Richness$month),]

saveRDS(Richness, file="COI/Local_analysis/output/RDS_files/Richness_df_all")

Richness_gal<-subset(Richness, Richness$source=="galloway")
Richness_exm<-subset(Richness, Richness$source=="exmoor")

#Calculate std error

Gal_agg<-aggregate( . ~ month, data=Richness_gal, std.error)
Exm_agg<-aggregate( . ~ month, data=Richness_exm, std.error)



se_gal<-c(rep(Gal_agg$Count[1], each=9),rep(Gal_agg$Count[2], each=10),rep(Gal_agg$Count[3], each=10),rep(Gal_agg$Count[4], each=10),rep(Gal_agg$Count[5], each=10),rep(Gal_agg$Count[6], each=10),rep(Gal_agg$Count[7], each=9),rep(Gal_agg$Count[8], each=10),rep(Gal_agg$Count[9], each=5),rep(Gal_agg$Count[10], each=10),rep(Gal_agg$Count[11], each=10),rep(Gal_agg$Count[12], each=10))

se_exm<-c(rep(Exm_agg$Count[1], each=11),rep(Exm_agg$Count[2], each=10),rep(Exm_agg$Count[3], each=10),rep(Exm_agg$Count[4], each=10),rep(Exm_agg$Count[5], each=10),rep(Exm_agg$Count[6], each=10),rep(Exm_agg$Count[7], each=11),rep(Exm_agg$Count[8], each=10),rep(Exm_agg$Count[9], each=15),rep(Exm_agg$Count[10], each=10),rep(Exm_agg$Count[11], each=10),rep(Exm_agg$Count[12], each=10))

Richness_gal<-cbind(Richness_gal, se_gal)
Richness_exm<-cbind(Richness_exm, se_exm)

Richness_gal[is.na(Richness_gal)]=0
Richness_exm[is.na(Richness_exm)]=0



#Set level order for plots
level_order <- c("January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December") 


#Plotting species richness over time
#Galloway
Species_Richness_gal<-ggplot(Richness_gal, aes(x=factor(month, level=level_order), y=Count, group=1)) +
  geom_point(stat="summary", fun=mean, col="darkorange") +
  geom_errorbar(stat="summary", aes(x=factor(month, level=level_order), ymin=Count-se_gal, ymax=Count+se_gal), width=0.5, col="darkorange") +
  #geom_errorbar(stat="summary", data=Richness_gal$Count[which(Richness_gal$month!="December")], aes(x=factor(Richness_gal$month[-which(Richness_gal$month=="December")], level=level_order), ymin=Richness_gal$Count-0.5, ymax=Richness_gal$Count+0.5), width=0.5, fun="mean_se") +
  scale_y_continuous(breaks=c(seq(0, 50, by = 5))) +
  stat_summary(fun=mean, geom="line", col="darkorange") +
  ggtitle("Species richness in cowpats") +
  theme_bw() +
  coord_cartesian(ylim=c(1,50)) +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), plot.title = element_text(hjust = 0.5)) +
  xlab("Month") +
  ylab("Number of species")

Species_Richness_gal

#Set level order for plots
#level_order <- c("January","February","April", "June", "August","December") 

level_order <- c("January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December") 

#Exmoor
Species_Richness_exm<-ggplot(Richness_exm, aes(x=factor(month, level=level_order), y=Count, group=1)) + 
  geom_point(stat="summary", fun=mean, col="darkred") +
  geom_errorbar(stat="summary", aes(x=factor(month, level=level_order), ymin=Count-se_exm, ymax=Count+se_exm), width=0.5, col="darkred") +
  #geom_point(stat="identity") +
  scale_y_continuous(breaks=c(seq(0, 50, by = 5))) +
  stat_summary(fun=mean, geom="line", col="darkred") +
  ggtitle("Species richness in horse dung") +
  theme_bw() +
  coord_cartesian(ylim=c(1,50)) +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), plot.title = element_text(hjust = 0.5)) +
  xlab("Month") +
  ylab("Number of species")

Species_Richness_exm

level_order <- c("January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December") 

dummy<-data.frame("Count"=c(rep(0,each=12)),"month"=level_order)

#Both
Species_Richness<-ggplot(dummy, aes(x=factor(month, level=level_order), y=Count, group=1)) + 
  geom_vline(xintercept="April",colour="white", linetype=2)+
  geom_vline(xintercept=4.5,colour="darkgrey", linetype=2)+
  geom_vline(xintercept=8.5,colour="darkgrey", linetype=2)+
  geom_point(data=Richness_gal, stat="summary", fun=mean, colour="darkorange",show.legend = TRUE) +
  geom_errorbar(data=Richness_gal, stat="summary", aes(x=factor(month, level=level_order), ymin=Count-se_gal, ymax=Count+se_gal), width=0.5, colour="darkorange") +
  geom_point(data=Richness_exm, stat="summary", fun=mean, colour="darkred", show.legend = TRUE) +
  geom_errorbar(data=Richness_exm, stat="summary", aes(x=factor(month, level=level_order), ymin=Count-se_exm, ymax=Count+se_exm), width=0.5, colour="darkred") +
  scale_y_continuous(breaks=c(seq(0,55, by=5))) +
  stat_summary(data=Richness_gal, fun=mean, geom="line", colour="darkorange") +
  stat_summary(data=Richness_exm, fun=mean, geom="line", colour="darkred") +
  #ggtitle("Species richness - dung associated coleopterans") +
  annotate("text", x=2.5, y=53, label="Early season", cex=3) +
  annotate("text", x=6.5, y=53, label ="Mid season", cex=3) +
  annotate("text", x=10.5, y=53, label="Late season", cex=3) +
  annotate("text", x=2.5, y=50, label=" ", cex=3) +
  annotate("text", x=6.5, y=50, label=" ", cex=3) +
  annotate("text", x=10.5, y=50, label=" ", cex=3) +
  theme_bw() +
  coord_cartesian(ylim=c(1,55)) +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), plot.title = element_text(hjust = 0.5)) +
  xlab("Month") +
  ylab("Number of species")

Species_Richness

ggarrange(Species_Richness, ncol = 1, nrow = 1)
ggsave("COI/Local_analysis/output/plots/SpeciesRichnessBothOneFig_all.pdf", width=10, height=6)


saveRDS(Species_Richness, file="COI/Local_analysis/output/RDS_files/Species_Richness")

ggarrange(Species_Richness_gal, Species_Richness_exm, labels = c("A", "B"), ncol = 1, nrow = 2)
ggsave("COI/Local_analysis/output/plots/SpeciesRichnessBoth_all.pdf", width=14, height=8)

RichnessBoth<-ggarrange(Species_Richness_gal, Species_Richness_exm, labels = c("A", "B"), ncol = 1, nrow = 2)

saveRDS(RichnessBoth, file="COI/Local_analysis/output/RDS_files/RichnessBoth")


#Find most abundant species across all samples

samples.data = read.table("COI/MetaBarFlow/output/Metadata_MOLS2020_invertebrates_corrected_source.txt",
                        header=TRUE,row.names=1,na.strings="NA")



source_vec<-c()
month_vec<-c()

for (i in 1:nrow(df_raw)) {
  sample<-as.character(df_raw$sample[i])
  idx<-which(row.names(samples.data)==sample)
  source_vec<-append(source_vec, as.character(samples.data$source[idx]))
  month_vec<-append(month_vec, as.character(samples.data$month[idx]))
}

source<-as.factor(source_vec)
month<-as.factor(month_vec)

df_raw<-cbind(df_raw, source, month)

df_gal<-subset(df_raw, df_raw$source=="galloway")
df_exm<-subset(df_raw, df_raw$source=="exmoor")

#Galloway
Species<-unique(df_gal$species)
abun<-list()

for (i in 1:length(Species)){
  df<-as.data.frame(Species[i])
  colnames(df)<-c("Species")
  Count<-sum(df_gal$count[df_gal$species==Species[i]])
  df<-cbind(df, Count)
  abun<-rbind(abun, df)
}

abundance<-abun[order(abun$Count),c(1,2)]

#Create vector of 20 most abundant species/ASVs
high_20_gal<-as.character(abundance$Species[(nrow(abundance)-19):(nrow(abundance))])

#Add "Other" as level in the df_raw$species vector
levels(df_gal$species) <- c(levels(df_gal$species),"Other")

#Check if species is in the 20 most abundant - if not, change species to "Other"
for (i in 1:nrow(df_gal)) {
  x<-as.character(df_gal$species[i])
  vec<-grepl(as.character(x), high_20_gal, fixed=TRUE)
  if (sum(vec)==0) {df_gal$species[i]="Other"     }
}


#Rename genus column to Genus
df_gal<-df_gal %>%
  dplyr::rename(Species=species)

#Change order of sampling time
df_gal<-df_gal %>%
  dplyr::mutate(sample=factor(sample, levels=c(  "JAN1","JAN2","JAN3","JAN4","JAN5","JAN6","JAN7","JAN8","JAN9","JAN10","JAN11","JAN12","JAN13","JAN14","JAN15","JAN16","JAN17","JAN18","JAN19","JAN20","FEB1","FEB2","FEB3","FEB4","FEB5","FEB6","FEB7","FEB8","FEB9","FEB10","FEB11","FEB12","FEB13","FEB14","FEB15","FEB16","FEB17","FEB18","FEB19","FEB20","MAR1","MAR2","MAR3","MAR4","MAR5","MAR6","MAR7","MAR8","MAR9","MAR10","MAR11","MAR12","MAR13","MAR14","MAR15","MAR16","MAR17","MAR18","MAR19","MAR20","APR1","APR2","APR3","APR4","APR5","APR6","APR7","APR8","APR9","APR10","APR11","APR12","APR13","APR14","APR15","APR16","APR17","APR18","APR19","APR20","MAY1","MAY2","MAY3","MAY4","MAY5","MAY6","MAY7","MAY8","MAY9","MAY10","MAY11","MAY12","MAY13","MAY14","MAY15","MAY16","MAY17","MAY18","MAY19","MAY20","JUN1","JUN2","JUN3","JUN4","JUN5","JUN6","JUN7","JUN8","JUN9","JUN10","JUN11","JUN12","JUN13","JUN14","JUN15","JUN16","JUN17","JUN18","JUN19","JUN20","JUL1","JUL2","JUL3","JUL4","JUL5","JUL6","JUL7","JUL8","JUL9","JUL10","JUL11","JUL12","JUL13","JUL14","JUL15","JUL16","JUL17","JUL18","JUL19","JUL20","AUG1","AUG2","AUG3","AUG4","AUG5","AUG6","AUG7","AUG8","AUG9","AUG10","AUG11","AUG12","AUG13","AUG14","AUG15","AUG16","AUG17","AUG18","AUG19","AUG20","SEP1","SEP2","SEP3","SEP4","SEP5","SEP6","SEP7","SEP8","SEP9","SEP10","SEP11","SEP12","SEP13","SEP14","SEP15","SEP16","SEP17","SEP18","SEP19","SEP20","OCT1","OCT2","OCT3","OCT4","OCT5","OCT6","OCT7","OCT8","OCT9","OCT10","OCT11","OCT12","OCT13","OCT14","OCT15","OCT16","OCT17","OCT18","OCT19","OCT20","NOV1","NOV2","NOV3","NOV4","NOV5","NOV6","NOV7","NOV8","NOV9","NOV10","NOV11","NOV12","NOV13","NOV14","NOV15","NOV16","NOV17","NOV18","NOV19","NOV20","DEC1","DEC2","DEC3","DEC4","DEC5","DEC6","DEC7","DEC8","DEC9","DEC10","DEC11","DEC12","DEC13","DEC14","DEC15","DEC16","DEC17","DEC18","DEC19","DEC20"
)))

levels<-append(sort(high_20_gal),"Other")

df_gal<-df_gal %>%
  dplyr::mutate(Species=factor(Species, levels=levels))


#Adding 21 color option
nb.cols <- 21
#mycolors <- colorRampPalette(brewer.pal(8, "Pastel2"))(nb.cols)
mycolorsbase <-c("darkolivegreen3","chocolate","brown2","darkolivegreen1","darkseagreen4","brown4","burlywood4","darkolivegreen","burlywood3","darkseagreen1","cornflowerblue","bisque4","chocolate1","yellow","darkorange4","burlywood1","brown","darkred","cyan","burlywood2","chartreuse3","darkkhaki","cadetblue4","goldenrod2","lightpink1","hotpink2","palegreen", "darkblue","darkmagenta","yellowgreen","magenta2","seagreen","mintcream","coral1","#aaffc3")
#mycolors<-c('#e6194B', '#3cb44b', '#ffe119', '#4363d8', '#f58231', '#911eb4', '#42d4f4', '#f032e6', '#bfef45', '#fabed4', '#469990', '#dcbeff', '#9A6324', '#fffac8', '#800000', '#aaffc3', '#808000', '#ffd8b1', '#000075', '#a9a9a9', '#000000')
mycolors<-mycolorsbase[c(1,3:4,6:9,11:12,23:25,27:29,31:35)]
mycolors<-append(mycolors,"black")

#Plotting Galloway
stacked_gal<-ggplot(df_gal, aes(fill=Species, y=freq, x=sample)) +
  guides(fill=guide_legend(ncol=2)) +
  geom_bar(position="stack", stat="identity") +
  scale_fill_manual(values = mycolors) +
  theme_bw()+
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),axis.text.x = element_text(angle = 90, vjust=0.5,hjust = 0.5),legend.text = element_text(colour="black", size = 10, face = "italic")) +
  xlab("Sample") +
  ylab("Relative frequency")



#Exmoor
Species<-unique(df_exm$species)
abun<-list()

for (i in 1:length(Species)){
  df<-as.data.frame(Species[i])
  colnames(df)<-c("Species")
  Count<-sum(df_exm$count[df_exm$species==Species[i]])
  df<-cbind(df, Count)
  abun<-rbind(abun, df)
}

abundance<-abun[order(abun$Count),c(1,2)]

#Create vector of 20 most abundant species/ASVs
high_20_exm<-as.character(abundance$Species[(nrow(abundance)-19):(nrow(abundance))])

#Add "Other" as level in the df_raw$species vector
levels(df_exm$species) <- c(levels(df_exm$species),"Other")

#Check if species is in the 20 most abundant - if not, change species to "Other"
for (i in 1:nrow(df_exm)) {
  x<-as.character(df_exm$species[i])
  vec<-grepl(as.character(x), high_20_exm, fixed=TRUE)
  if (sum(vec)==0) {df_exm$species[i]="Other"     }
}


#Rename genus column to Genus
df_exm<-df_exm %>%
  dplyr::rename(Species=species)

#Change order of sampling time
df_exm<-df_exm %>%
  dplyr::mutate(sample=factor(sample, levels=c(  "JAN1","JAN2","JAN3","JAN4","JAN5","JAN6","JAN7","JAN8","JAN9","JAN10","JAN11","JAN12","JAN13","JAN14","JAN15","JAN16","JAN17","JAN18","JAN19","JAN20","FEB1","FEB2","FEB3","FEB4","FEB5","FEB6","FEB7","FEB8","FEB9","FEB10","FEB11","FEB12","FEB13","FEB14","FEB15","FEB16","FEB17","FEB18","FEB19","FEB20","MAR1","MAR2","MAR3","MAR4","MAR5","MAR6","MAR7","MAR8","MAR9","MAR10","MAR11","MAR12","MAR13","MAR14","MAR15","MAR16","MAR17","MAR18","MAR19","MAR20","APR1","APR2","APR3","APR4","APR5","APR6","APR7","APR8","APR9","APR10","APR11","APR12","APR13","APR14","APR15","APR16","APR17","APR18","APR19","APR20","MAY1","MAY2","MAY3","MAY4","MAY5","MAY6","MAY7","MAY8","MAY9","MAY10","MAY11","MAY12","MAY13","MAY14","MAY15","MAY16","MAY17","MAY18","MAY19","MAY20","JUN1","JUN2","JUN3","JUN4","JUN5","JUN6","JUN7","JUN8","JUN9","JUN10","JUN11","JUN12","JUN13","JUN14","JUN15","JUN16","JUN17","JUN18","JUN19","JUN20","JUL1","JUL2","JUL3","JUL4","JUL5","JUL6","JUL7","JUL8","JUL9","JUL10","JUL11","JUL12","JUL13","JUL14","JUL15","JUL16","JUL17","JUL18","JUL19","JUL20","AUG1","AUG2","AUG3","AUG4","AUG5","AUG6","AUG7","AUG8","AUG9","AUG10","AUG11","AUG12","AUG13","AUG14","AUG15","AUG16","AUG17","AUG18","AUG19","AUG20","SEP1","SEP2","SEP3","SEP4","SEP5","SEP6","SEP7","SEP8","SEP9","SEP10","SEP11","SEP12","SEP13","SEP14","SEP15","SEP16","SEP17","SEP18","SEP19","SEP20","OCT1","OCT2","OCT3","OCT4","OCT5","OCT6","OCT7","OCT8","OCT9","OCT10","OCT11","OCT12","OCT13","OCT14","OCT15","OCT16","OCT17","OCT18","OCT19","OCT20","NOV1","NOV2","NOV3","NOV4","NOV5","NOV6","NOV7","NOV8","NOV9","NOV10","NOV11","NOV12","NOV13","NOV14","NOV15","NOV16","NOV17","NOV18","NOV19","NOV20","DEC1","DEC2","DEC3","DEC4","DEC5","DEC6","DEC7","DEC8","DEC9","DEC10","DEC11","DEC12","DEC13","DEC14","DEC15","DEC16","DEC17","DEC18","DEC19","DEC20"
)))

levels<-append(sort(high_20_exm),"Other")


df_exm<-df_exm %>%
  dplyr::mutate(Species=factor(Species, levels=levels))


mycolors<-mycolorsbase[c(2,4:5,9:10,12:23,26,28,30)]
mycolors<-append(mycolors,"black")

#Plotting Exmoor
stacked_exm<-ggplot(df_exm, aes(fill=Species, y=freq, x=sample)) +
  guides(fill=guide_legend(ncol=2)) +
  geom_bar(position="stack", stat="identity") +
  scale_fill_manual(values = mycolors) +
  theme_bw()+
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),axis.text.x = element_text(angle = 90, vjust=0.5,hjust = 0.5),legend.text = element_text(colour="black", size = 10, face = "italic")) +
  xlab("Sample") +
  ylab("Relative frequency")


write.csv(cbind(sort(high_20_exm),sort(high_20_gal)), file="COI/Local_analysis/output/tables/high-20_dung_all_metazoa.csv")


ggarrange(stacked_gal,stacked_exm, labels = c("A", "B"), ncol = 1, nrow = 2)
ggsave("COI/Local_analysis/output/plots/StackedBothSpecies_all.pdf", width=14, height=8)



StackedBoth<-ggarrange(stacked_gal,stacked_exm, labels = c("A", "B"), ncol = 1, nrow = 2)

saveRDS(StackedBoth, file="COI/Local_analysis/output/RDS_files/StackedBothSpecies_all")

#Aggregate samples by month

gal_month<-aggregate(df_gal, list(Month = df_gal$month, Species = df_gal$Species), FUN=mean)
exm_month<-aggregate(df_exm, list(Month = df_exm$month, Species = df_exm$Species), FUN=mean)

#Remove redundant columns
gal_month<-gal_month[,-c(3:4,6:9)]
exm_month<-exm_month[,-c(3:4,6:9)]

gal_month_20<-gal_month
exm_month_20<-exm_month

#Calculate total reads in each month

jan<-c()
feb<-c()
mar<-c()
apr<-c()
may<-c()
jun<-c()
jul<-c()
aug<-c()
sep<-c()
oct<-c()
nov<-c()
dec<-c()
for (i in 1:nrow(gal_month)) {
  if (gal_month$Month[i]=="January") {jan<-append(jan, gal_month$count[i])}
  if (gal_month$Month[i]=="February") {feb<-append(feb, gal_month$count[i])}
  if (gal_month$Month[i]=="March") {mar<-append(mar, gal_month$count[i])}
  if (gal_month$Month[i]=="April") {apr<-append(apr, gal_month$count[i])}
  if (gal_month$Month[i]=="May") {may<-append(may, gal_month$count[i])}
  if (gal_month$Month[i]=="June") {jun<-append(jun, gal_month$count[i])}
  if (gal_month$Month[i]=="July") {jul<-append(jul, gal_month$count[i])}
  if (gal_month$Month[i]=="August") {aug<-append(aug, gal_month$count[i])}
  if (gal_month$Month[i]=="September") {sep<-append(sep, gal_month$count[i])}
  if (gal_month$Month[i]=="October") {oct<-append(oct, gal_month$count[i])}
  if (gal_month$Month[i]=="November") {nov<-append(nov, gal_month$count[i])}
  if (gal_month$Month[i]=="December") {dec<-append(dec, gal_month$count[i])}
}
total_each_gal<-sapply(list(jan,feb,mar,apr,may,jun,jul,aug,sep,oct,nov,dec), FUN=sum)

totalreads<-c(rep(1, each=nrow(gal_month)))

gal_month<-cbind(gal_month, totalreads)

for (i in 1:nrow(gal_month)) {
  if (gal_month$Month[i]=="January") {gal_month$totalreads[i]=total_each_gal[1]}
  if (gal_month$Month[i]=="February") {gal_month$totalreads[i]=total_each_gal[2]}
  if (gal_month$Month[i]=="March") {gal_month$totalreads[i]=total_each_gal[3]}
  if (gal_month$Month[i]=="April") {gal_month$totalreads[i]=total_each_gal[4]}
  if (gal_month$Month[i]=="May") {gal_month$totalreads[i]=total_each_gal[5]}
  if (gal_month$Month[i]=="June") {gal_month$totalreads[i]=total_each_gal[6]}
  if (gal_month$Month[i]=="July") {gal_month$totalreads[i]=total_each_gal[7]}
  if (gal_month$Month[i]=="August") {gal_month$totalreads[i]=total_each_gal[8]}
  if (gal_month$Month[i]=="September") {gal_month$totalreads[i]=total_each_gal[9]}
  if (gal_month$Month[i]=="October") {gal_month$totalreads[i]=total_each_gal[10]}
  if (gal_month$Month[i]=="November") {gal_month$totalreads[i]=total_each_gal[11]}
  if (gal_month$Month[i]=="December") {gal_month$totalreads[i]=total_each_gal[12]}
  }

freq<-c()

for (i in 1:nrow(gal_month)) {
  x<-gal_month$count[i]/gal_month$totalreads[i]
  freq<-append(freq,x)
}

gal_month<-cbind(gal_month, freq)

#And for exmoor ponies


jan<-c()
feb<-c()
mar<-c()
apr<-c()
may<-c()
jun<-c()
jul<-c()
aug<-c()
sep<-c()
oct<-c()
nov<-c()
dec<-c()

for (i in 1:nrow(exm_month)) {
  if (exm_month$Month[i]=="January") {jan<-append(jan, exm_month$count[i])}
  if (exm_month$Month[i]=="February") {feb<-append(feb, exm_month$count[i])}
  if (exm_month$Month[i]=="March") {mar<-append(mar, exm_month$count[i])}
  if (exm_month$Month[i]=="April") {apr<-append(apr, exm_month$count[i])}
  if (exm_month$Month[i]=="May") {may<-append(may, exm_month$count[i])}
  if (exm_month$Month[i]=="June") {jun<-append(jun, exm_month$count[i])}
  if (exm_month$Month[i]=="July") {jul<-append(jul, exm_month$count[i])}
  if (exm_month$Month[i]=="August") {aug<-append(aug, exm_month$count[i])}
  if (exm_month$Month[i]=="September") {sep<-append(sep, exm_month$count[i])}
  if (exm_month$Month[i]=="October") {oct<-append(oct, exm_month$count[i])}
  if (exm_month$Month[i]=="November") {nov<-append(nov, exm_month$count[i])}
  if (exm_month$Month[i]=="December") {dec<-append(dec, exm_month$count[i])}
}
total_each_exm<-sapply(list(jan,feb,mar,apr,may,jun,jul,aug,sep,oct,nov,dec), FUN=sum)

totalreads<-c(rep(1, each=nrow(exm_month)))

exm_month<-cbind(exm_month, totalreads)

for (i in 1:nrow(exm_month)) {
  if (exm_month$Month[i]=="January") {exm_month$totalreads[i]=total_each_exm[1]}
  if (exm_month$Month[i]=="February") {exm_month$totalreads[i]=total_each_exm[2]}
  if (exm_month$Month[i]=="March") {exm_month$totalreads[i]=total_each_exm[3]}
  if (exm_month$Month[i]=="April") {exm_month$totalreads[i]=total_each_exm[4]}
  if (exm_month$Month[i]=="May") {exm_month$totalreads[i]=total_each_exm[5]}
  if (exm_month$Month[i]=="June") {exm_month$totalreads[i]=total_each_exm[6]}
  if (exm_month$Month[i]=="July") {exm_month$totalreads[i]=total_each_exm[7]}
  if (exm_month$Month[i]=="August") {exm_month$totalreads[i]=total_each_exm[8]}
  if (exm_month$Month[i]=="September") {exm_month$totalreads[i]=total_each_exm[9]}
  if (exm_month$Month[i]=="October") {exm_month$totalreads[i]=total_each_exm[10]}
  if (exm_month$Month[i]=="November") {exm_month$totalreads[i]=total_each_exm[11]}
  if (exm_month$Month[i]=="December") {exm_month$totalreads[i]=total_each_exm[12]}
  }

freq<-c()

for (i in 1:nrow(exm_month)) {
  x<-exm_month$count[i]/exm_month$totalreads[i]
  freq<-append(freq,x)
}

exm_month<-cbind(exm_month, freq)

mycolors<-mycolorsbase[c(1,3:4,6:9,11:12,23:25,27:29,31:35)]
mycolors<-append(mycolors,"black")


#Plotting Galloway
stacked_gal_months<-ggplot(gal_month, aes(fill=Species, y=freq, x=factor(Month, level=level_order))) +
  guides(fill=guide_legend(ncol=2)) +
  geom_bar(position="stack", stat="identity") +
  scale_fill_manual(values = mycolors) +
  theme_bw()+
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),axis.text.x = element_text(angle = 90, vjust=0.5,hjust = 0.5),legend.text = element_text(colour="black", size = 10, face = "italic")) +
  xlab("Month") +
  ylab("Relative frequency")

mycolors<-mycolorsbase[c(2,4:5,9:10,12:23,26,28,30)]
mycolors<-append(mycolors,"black")

#Plotting Exmoor
stacked_exm_months<-ggplot(exm_month, aes(fill=Species, y=freq, x=factor(Month, level=level_order))) +
  guides(fill=guide_legend(ncol=2)) +
  geom_bar(position="stack", stat="identity") +
  scale_fill_manual(values = mycolors) +
  theme_bw()+
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),axis.text.x = element_text(angle = 90, vjust=0.5,hjust = 0.5),legend.text = element_text(colour="black", size = 10, face = "italic")) +
  xlab("Month") +
  ylab("Relative frequency")



ggarrange(stacked_gal_months, stacked_exm_months, labels = c("A", "B"), ncol = 1, nrow = 2)
ggsave("COI/Local_analysis/output/plots/StackedBothMonthsSpecies_all.pdf", width=14, height=8)


StackedBothMonths<-ggarrange(stacked_gal_months, stacked_exm_months, labels = c("A", "B"), ncol = 1, nrow = 2)

saveRDS(StackedBothMonths, file="COI/Local_analysis/output/RDS_files/StackedBothMonthsSpecies_all")


#By nematodes vs. arthropods

n<-count(gal_month, Species)


type<-rep(c("Nematoda","Arthropoda","Arthropoda","Mammalia",
            "Arthropoda","Nematoda","Arthropoda","Nematoda",
            "Arthropoda","Arthropoda","Arthropoda","Arthropoda",
            "Arthropoda","Nematoda","Nematoda","Arthropoda",
            "Arthropoda","Arthropoda","Arthropoda","Arthropoda",
            "Unknown"), times=c(n$n))


gal_nema<-cbind(gal_month, "type"=factor(type, levels =c("Arthropoda","Mammalia","Nematoda","Unknown") ))

n<-count(exm_month, Species)


type<-rep(c("Arthropoda","Arthropoda","Arthropoda","Arthropoda",
            "Annelida","Arthropoda","Nematoda","Nematoda",
            "Nematoda","Nematoda","Nematoda","Nematoda",
            "Nematoda","Nematoda","Nematoda","Nematoda",
            "Arthropoda","Arthropoda","Nematoda","Arthropoda",
            "Unknown"), times=c(n$n))


exm_nema<-cbind(exm_month, "type"=factor(type, levels =c("Annelida","Arthropoda","Mammalia","Nematoda","Unknown") ))


mycolors<-mycolorsbase[c(2:4)]
mycolors<-append(mycolors,"black")


#Plotting Galloway
stacked_gal_nema<-ggplot(gal_nema, aes(fill=type, y=freq, x=factor(Month, level=level_order))) +
  guides(fill=guide_legend(ncol=1)) +
  geom_bar(position="stack", stat="identity") +
  scale_fill_manual(values = mycolors) +
  theme_bw()+
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),axis.text.x = element_text(angle = 90, vjust=0.5,hjust = 0.5),legend.text = element_text(colour="black", size = 10, face = "italic")) +
  xlab("Month") +
  ylab("Proportion of reads")

mycolors<-mycolorsbase[c(1:2,4)]
mycolors<-append(mycolors,"black")

#Plotting Exmoor
stacked_exm_nema<-ggplot(exm_nema, aes(fill=type, y=freq, x=factor(Month, level=level_order))) +
  guides(fill=guide_legend(ncol=1)) +
  geom_bar(position="stack", stat="identity") +
  scale_fill_manual(values = mycolors) +
  theme_bw()+
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),axis.text.x = element_text(angle = 90, vjust=0.5,hjust = 0.5),legend.text = element_text(colour="black", size = 10, face = "italic")) +
  xlab("Month") +
  ylab("Proportion of reads")


stacked_gal_nema

stacked_exm_nema

ggarrange(stacked_gal_nema, stacked_exm_nema, labels = c("A", "B"), ncol = 1, nrow = 2)
ggsave("COI/Local_analysis/output/figures/nema_vs_arthro.png", width=14, height=8)



```

```{r Find unique species}



#Loading libraries
library(tidyverse)
library(ROBITools)
library(ROBITaxonomy)
library(ggpubr)
library(dplyr)
library(ggplot2)
library(ggsci)
library(RColorBrewer)

#Set level order for plots
level_order <- c("January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December") 

#Load data
df_raw <- readRDS("COI/Local_analysis/output/RDS_files/df_for_plots_and_analysis_all")

dataset<-readRDS("COI/Local_analysis/output/RDS_files/dataset_final")

df_gal<-dataset@reads[which(dataset@samples$source=="galloway"),]
colnames(df_gal)<-dataset@motus$final.otu
df_exm<-dataset@reads[which(dataset@samples$source=="exmoor"),]
colnames(df_exm)<-dataset@motus$final.otu
df_open<-dataset@reads[which(dataset@samples$habitat=="open"),]
colnames(df_open)<-dataset@motus$final.otu
df_forest<-dataset@reads[which(dataset@samples$habitat=="forest"),]
colnames(df_forest)<-dataset@motus$final.otu

df_gal_open<-dataset@reads[which(dataset@samples$source=="galloway" & dataset@samples$habitat=="open"),]
colnames(df_gal_open)<-dataset@motus$final.otu
df_gal_forest<-dataset@reads[which(dataset@samples$source=="galloway" & dataset@samples$habitat=="forest"),]
colnames(df_gal_forest)<-dataset@motus$final.otu
df_exm_open<-dataset@reads[which(dataset@samples$source=="exmoor" & dataset@samples$habitat=="open"),]
colnames(df_exm_open)<-dataset@motus$final.otu
df_exm_forest<-dataset@reads[which(dataset@samples$source=="exmoor" & dataset@samples$habitat=="forest"),]
colnames(df_exm_forest)<-dataset@motus$final.otu


gal_species<-c()
exm_species<-c()
open_species<-c()
forest_species<-c()
for (i in 1:ncol(df_gal)) {
  if (sum(df_gal[,i])>0) {gal_species<-append(gal_species,colnames(df_gal)[i])}
  if (sum(df_exm[,i])>0) {exm_species<-append(exm_species,colnames(df_exm)[i])}
  if (sum(df_open[,i])>0) {open_species<-append(open_species,colnames(df_open)[i])}
  if (sum(df_forest[,i])>0) {forest_species<-append(forest_species,colnames(df_forest)[i])}
  
}


gal_open<-c()
gal_forest<-c()
exm_open<-c()
exm_forest<-c()
for (i in 1:ncol(df_gal_open)) {
  if (sum(df_gal_open[,i])>0) {gal_open<-append(gal_open,colnames(df_gal_open)[i])}
  if (sum(df_gal_forest[,i])>0) {gal_forest<-append(gal_forest,colnames(df_gal_forest)[i])}
  if (sum(df_exm_open[,i])>0) {exm_open<-append(exm_open,colnames(df_exm_open)[i])}
  if (sum(df_exm_forest[,i])>0) {exm_forest<-append(exm_forest,colnames(df_exm_forest)[i])}
  
}


open_uniq<-setdiff(open_species, forest_species)
forest_uniq<-setdiff(forest_species,open_species)


gal_uniq<-setdiff(gal_species, exm_species)
exm_uniq<-setdiff(exm_species,gal_species)

mx<-max(length(open_uniq),length(forest_uniq),length(gal_uniq),length(exm_uniq))


unique<-data.frame("open"=append(open_uniq,rep(0, each=mx-length(open_uniq))),
                   "forest"=append(forest_uniq,rep(0, each=mx-length(forest_uniq))), 
                   "galloway"=append(gal_uniq,rep(0, each=mx-length(gal_uniq))), 
                   "exmoor"=append(exm_uniq,rep(0, each=mx-length(exm_uniq))))

write.csv2(unique, file="COI/Local_analysis/output/tables/unique_all.csv")


#Create Venn diagram


library("ggVennDiagram")

x <- list(
  Galloway = gal_species, 
  Exmoor = exm_species,
  Open = open_species,
  Forest = forest_species
)

y <- list(
  GO = gal_open, 
  GF = gal_forest,
  EO = exm_open,
  EF = exm_forest
) 


venn1 <- ggVennDiagram(
  x[1:2], label_alpha = 0,
  category.names = c("Galloway","Exmoor"),
  edge_lty = "blank") +
  ggplot2::scale_fill_gradient2(low="#FDE725FF",high = "#440154FF", mid="#29AF7FFF", midpoint = 160)

venn1

venn2 <- ggVennDiagram(
  x[3:4], label_alpha = 0,
  category.names = c("Open","Forest"),
  edge_lty = "blank") +
  ggplot2::scale_fill_gradient2(low="#FDE725FF",high = "#440154FF", mid="#29AF7FFF", midpoint = 170)

venn2

venn3 <- ggVennDiagram(
  y, label_alpha = 0,
  category.names = c("Galloway - open","Galloway - forest","Exmoor - open","Exmoor - forest"),
  edge_lty = "blank") +
  ggplot2::scale_fill_gradient2(low="#FDE725FF",high = "#440154FF", mid="#29AF7FFF", midpoint = 65)

venn3

ggarrange(venn1,venn2,venn3, labels = c("A", "B","C"), ncol = 1, nrow = 3)
ggsave("COI/Local_analysis/output/plots/venn_diagrams_all.pdf", width=5, height=8)



```

```{r NDMS plots}

#Libraries
library(vegan)
library(dplyr)
library(ggplot2)
library(ggalt)
library(ggpubr)
#library(BiodiversityR)

#Function for inverse normal transformation
inormal <- function(x)
{
  qnorm((rank(x, na.last = "keep") - 0.5) / sum(!is.na(x)))
}

#This step plots CAP and NMDS plots of abundance and presence/absence data
dataset <- readRDS("COI/Local_analysis/output/RDS_files/dataset_final")

par(mfrow=c(1,1))

samples<-dataset@samples[,c("source", "habitat","month")]

season_vec=c()
for (i in 1:nrow(samples)) {
  if (samples$month[i]=="January") {season_vec<-append(season_vec,"early")} 
  else if (samples$month[i]=="February") {season_vec<-append(season_vec,"early")} 
  else if (samples$month[i]=="March") {season_vec<-append(season_vec,"early")}
  else if (samples$month[i]=="April") {season_vec<-append(season_vec,"early")}
  else if (samples$month[i]=="May") {season_vec<-append(season_vec,"mid")}
  else if (samples$month[i]=="June") {season_vec<-append(season_vec,"mid")}
  else if (samples$month[i]=="July") {season_vec<-append(season_vec,"mid")}
  else if (samples$month[i]=="August") {season_vec<-append(season_vec,"mid")}
  else if (samples$month[i]=="September") {season_vec<-append(season_vec,"late")}
  else if (samples$month[i]=="October") {season_vec<-append(season_vec,"late")}
  else if (samples$month[i]=="November") {season_vec<-append(season_vec,"late")}
  else if (samples$month[i]=="December") {season_vec<-append(season_vec,"late")}
}
samples<-cbind(samples, "season"=season_vec)

group<-c()
for (i in 1:nrow(samples)) {
  if (samples$source[i]=="galloway" && samples$season[i]=="early" && samples$habitat[i]=="open") {group<-append(group,"Galloway - EarlyOpen")}
  if (samples$source[i]=="galloway" && samples$season[i]=="early" && samples$habitat[i]=="forest") {group<-append(group,"Galloway - EarlyForest")}
  if (samples$source[i]=="galloway" && samples$season[i]=="mid" && samples$habitat[i]=="open") {group<-append(group,"Galloway - MidOpen")}
  if (samples$source[i]=="galloway" && samples$season[i]=="mid" && samples$habitat[i]=="forest") {group<-append(group,"Galloway - MidForest")}
  if (samples$source[i]=="galloway" && samples$season[i]=="late" && samples$habitat[i]=="open") {group<-append(group,"Galloway - LateOpen")}
  if (samples$source[i]=="galloway" && samples$season[i]=="late" && samples$habitat[i]=="forest") {group<-append(group,"Galloway - LateForest")}
  if (samples$source[i]=="exmoor" && samples$season[i]=="early" && samples$habitat[i]=="open") {group<-append(group,"Exmoor - EarlyOpen")}
  if (samples$source[i]=="exmoor" && samples$season[i]=="early" && samples$habitat[i]=="forest") {group<-append(group,"Exmoor - EarlyForest")}
  if (samples$source[i]=="exmoor" && samples$season[i]=="mid" && samples$habitat[i]=="open") {group<-append(group,"Exmoor - MidOpen")}
  if (samples$source[i]=="exmoor" && samples$season[i]=="mid" && samples$habitat[i]=="forest") {group<-append(group,"Exmoor - MidForest")}
  if (samples$source[i]=="exmoor" && samples$season[i]=="late" && samples$habitat[i]=="open") {group<-append(group,"Exmoor - LateOpen")}
  if (samples$source[i]=="exmoor" && samples$season[i]=="late" && samples$habitat[i]=="forest") {group<-append(group,"Exmoor - LateForest")}
}

samples<-cbind(samples,group)


group2<-c()
for (i in 1:nrow(samples)) {
  if (samples$source[i]=="galloway" && samples$habitat[i]=="open") {group2<-append(group2,"Galloway - Open")}
  if (samples$source[i]=="galloway" && samples$habitat[i]=="forest") {group2<-append(group2,"Galloway - Forest")}
  if (samples$source[i]=="exmoor" && samples$habitat[i]=="open") {group2<-append(group2,"Exmoor - Open")}
  if (samples$source[i]=="exmoor" && samples$habitat[i]=="forest") {group2<-append(group2,"Exmoor - Forest")}
}


group3<-c()
for (i in 1:nrow(samples)) {
  if (samples$source[i]=="galloway" && samples$season[i]=="early") {group3<-append(group3,"Galloway - Early")}
  if (samples$source[i]=="galloway" && samples$season[i]=="mid") {group3<-append(group3,"Galloway - Mid")}
  if (samples$source[i]=="galloway" && samples$season[i]=="late") {group3<-append(group3,"Galloway - Late")}
  if (samples$source[i]=="exmoor" && samples$season[i]=="early") {group3<-append(group3,"Exmoor - Early")}
  if (samples$source[i]=="exmoor" && samples$season[i]=="mid") {group3<-append(group3,"Exmoor - Mid")}
  if (samples$source[i]=="exmoor" && samples$season[i]=="late") {group3<-append(group3,"Exmoor - Late")}
}





samples<-cbind(samples,group2,group3)

reads<-dataset$reads

#Evaluate number of dimensions

mreads<-as.matrix(sqrt(reads))
#mreads<-as.matrix(reads) #With or without transformation?
nmds1D = metaMDS(mreads, distance = "bray", k=1)
nmds2D = metaMDS(mreads, distance = "bray", k=2)
nmds3D = metaMDS(mreads, distance = "bray", k=3)
nmds4D = metaMDS(mreads, distance = "bray", k=4)
nmds5D = metaMDS(mreads, distance = "bray", k=5)
nmds20D = metaMDS(mreads, distance = "bray", k=20)

dim<-data.frame("dim"=c(1,2,3,4,5,20),"stress"=c(nmds1D$stress,nmds2D$stress,nmds3D$stress,nmds4D$stress,nmds5D$stress,nmds20D$stress))

plot(dim$dim,dim$stress, main="Stress values in nMDS ordination with increasing numbers of dimensions", cex.main=0.8)
abline(h=0.20, col="red", lty=2)

par(mfrow=c(2,2))
stressplot(nmds1D, main="Stressplot K=1")
stressplot(nmds2D, main="Stressplot K=2")
stressplot(nmds3D, main="Stressplot K=3")
stressplot(nmds4D, main="Stressplot K=4")
stressplot(nmds5D, main="Stressplot K=5")
stressplot(nmds20D, main="Stressplot K=20")


#From stress vs. dimension plot, and stressplots, it seems that 2 dimensions will be appropriate (non-metric fit R2>0.963, stress<0.1913)

reads<-dataset$reads

#Perform NMDS-plot of reads
mreads<-as.matrix(sqrt(reads))
#mreads<-as.matrix(reads) #With or without transformation?
nmds = metaMDS(mreads, distance = "bray")
nmds.scores = as.data.frame(vegan::scores(nmds))
head(nmds.scores)

nmds.scores$Sample = row.names(samples)
nmds.scores$Source = samples$source
nmds.scores$Habitat = samples$habitat
nmds.scores$Month = samples$month
nmds.scores$Season = samples$season
nmds.scores$Group = samples$group

nmds.scores<-nmds.scores %>%
  dplyr::mutate(Source=factor(Source, levels=c("galloway","exmoor")))

gg1<-ggplot(nmds.scores, aes(x = NMDS1, y = NMDS2)) + 
  geom_point(size = 3, aes(colour = Source)) +
  scale_color_manual(values=c("darkorange","darkred")) +
  geom_encircle(aes(fill = Source), s_shape = 1, expand = 0,
                alpha = 0.2, color = "black", show.legend = FALSE) +
  scale_fill_manual(values=c("darkorange","darkred")) +
  annotate("text", x=0, y=2, label="All samples - all metazoans", cex=3) +
  annotate("text", x=0, y=1.8, label="(Squareroot - transformed read counts)", cex=3) +
  theme_bw()

plot(gg1)




# https://jkzorz.github.io/2019/06/06/NMDS.html 
# https://stackoverflow.com/questions/52289812/group-geom-point-with-the-geom-polygon/52290514?fbclid=IwAR0xPB5W9fZc3dYb8868fJ_SiKgb9WPXVofZsrn-HsfJd1KEoVRkW52qQk0
# ANOSIM statistical test of differences between community data: https://jkzorz.github.io/2019/06/11/ANOSIM-test.html
#PERMANOVA: https://archetypalecology.wordpress.com/2018/02/21/permutational-multivariate-analysis-of-variance-permanova-in-r-preliminary/

#Presence/Absence
#Perform NMDS-plot of reads
reads[reads>0]<-1
#mreads<-as.matrix(sqrt(reads))
mreads<-as.matrix(reads) #transformation doesn't matter for presence absence data
nmds = metaMDS(mreads, distance = "bray")
nmds.scores = as.data.frame(vegan::scores(nmds))
head(nmds.scores)

nmds.scores$Sample = row.names(samples)
nmds.scores$Source = samples$source
nmds.scores$Habitat = samples$habitat
nmds.scores$Month = samples$month
nmds.scores$Season = samples$season
nmds.scores$Group = samples$group

nmds.scores<-nmds.scores %>%
  dplyr::mutate(Source=factor(Source, levels=c("galloway","exmoor")))

gg2<-ggplot(nmds.scores, aes(x = NMDS1, y = NMDS2)) + 
  geom_point(size = 3, aes(colour = Source)) +
  scale_color_manual(values=c("darkorange","darkred")) +
  geom_encircle(aes(fill = Source), s_shape = 1, expand = 0,
                alpha = 0.2, color = "black", show.legend = FALSE) +
  scale_fill_manual(values=c("darkorange","darkred")) +
  annotate("text", x=0, y=2, label="All samples - all metazoans", cex=3) +
  annotate("text", x=0, y=1.8, label="(Presence/absence)", cex=3) +
  theme_bw()

plot(gg2)

# https://jkzorz.github.io/2019/06/06/NMDS.html 
# https://stackoverflow.com/questions/52289812/group-geom-point-with-the-geom-polygon/52290514?fbclid=IwAR0xPB5W9fZc3dYb8868fJ_SiKgb9WPXVofZsrn-HsfJd1KEoVRkW52qQk0

#Perform NMDS-plot of reads
reads<-dataset$reads

mreads<-as.matrix(sqrt(reads))
#mreads<-as.matrix(reads) #With or without transformation?
nmds = metaMDS(mreads, distance = "bray")
nmds.scores = as.data.frame(vegan::scores(nmds))
head(nmds.scores)

nmds.scores$Sample = row.names(samples)
nmds.scores$Source = samples$source
nmds.scores$Habitat = samples$habitat
nmds.scores$Month = samples$month
nmds.scores$Season = samples$season
nmds.scores$Group = samples$group2

nmds.scores<-nmds.scores %>%
  dplyr::mutate(Habitat=factor(Habitat, levels=c("open","forest")))

gg3<-ggplot(nmds.scores, aes(x = NMDS1, y = NMDS2)) + 
  geom_point(size = 3, aes(colour = Habitat)) +
  scale_color_manual(values=c("gold1","darkgreen","palegreen","darkgoldenrod")) +
  geom_encircle(aes(fill = Habitat), s_shape = 1, expand = 0,
                alpha = 0.2, color = "black", show.legend = FALSE) +
  scale_fill_manual(values=c("gold1","darkgreen","palegreen","darkgoldenrod")) +
  annotate("text", x=0, y=2, label="All samples - all metazoans", cex=3) +
  annotate("text", x=0, y=1.8, label="(Squareroot - transformed read counts)", cex=3) +
  theme_bw()

plot(gg3)


#Presence/Absence
#Perform NMDS-plot of reads
reads[reads>0]<-1
#mreads<-as.matrix(sqrt(reads))
mreads<-as.matrix(reads) #transformation doesn't matter for presence absence data
nmds = metaMDS(mreads, distance = "bray")
nmds.scores = as.data.frame(vegan::scores(nmds))
head(nmds.scores)

nmds.scores$Sample = row.names(samples)
nmds.scores$Source = samples$source
nmds.scores$Habitat = samples$habitat
nmds.scores$Month = samples$month

nmds.scores<-nmds.scores %>%
  dplyr::mutate(Habitat=factor(Habitat, levels=c("open", "forest")))

gg4<-ggplot(nmds.scores, aes(x = NMDS1, y = NMDS2)) + 
  geom_point(size = 3, aes(colour = Habitat)) +
  scale_color_manual(values=c("gold1","darkgreen")) +
  geom_encircle(aes(fill = Habitat), s_shape = 1, expand = 0,
                alpha = 0.2, color = "black", show.legend = FALSE) +
  scale_fill_manual(values=c("gold1","darkgreen")) +
  annotate("text", x=0, y=2, label="All samples - all metazoans", cex=3) +
  annotate("text", x=0, y=1.8, label="(Presence/absence)", cex=3) +
  theme_bw()

plot(gg4)


#Perform NMDS-plot of reads
reads<-dataset$reads

mreads<-as.matrix(sqrt(reads))
#mreads<-as.matrix(reads) #With or without transformation?
nmds = metaMDS(mreads, distance = "bray")
nmds.scores = as.data.frame(vegan::scores(nmds))
head(nmds.scores)

nmds.scores$Sample = row.names(samples)
nmds.scores$Source = samples$source
nmds.scores$Habitat = samples$habitat
nmds.scores$Month = samples$month

nmds.scores<-nmds.scores %>%
  dplyr::mutate(Month=factor(Month, levels=c("January","February","March","April","May","June","July","August","September","October","November","December")))

gg5<-ggplot(nmds.scores, aes(x = NMDS1, y = NMDS2)) + 
  geom_point(size = 3, aes(colour = Month)) +
  scale_color_manual(values=c("lightskyblue1","lightskyblue3","lightgreen","palegreen4","olivedrab","orange2","darkorange3","firebrick2","burlywood4","burlywood3","tan","dodgerblue")) +
  geom_encircle(aes(fill = Month), s_shape = 1, expand = 0,
                alpha = 0.2, color = "black", show.legend = FALSE) +
  scale_fill_manual(values=c("lightskyblue1","lightskyblue3","lightgreen","palegreen4","olivedrab","orange2","darkorange3","firebrick2","burlywood4","burlywood3","tan","dodgerblue")) +
  coord_cartesian(xlim=c(-4.8,4.1),ylim=c(-2.5,2.5)) +
  theme_bw()

plot(gg5)

#Presence/Absence
#Perform NMDS-plot of reads
reads[reads>0]<-1
#mreads<-as.matrix(sqrt(reads))
mreads<-as.matrix(reads) #transformation doesn't matter for presence absence data
nmds = metaMDS(mreads, distance = "bray")
nmds.scores = as.data.frame(vegan::scores(nmds))
head(nmds.scores)

nmds.scores$Sample = row.names(samples)
nmds.scores$Source = samples$source
nmds.scores$Habitat = samples$habitat
nmds.scores$Month = samples$month

nmds.scores<-nmds.scores %>%
  dplyr::mutate(Month=factor(Month, levels=c("January","February","March","April","May","June","July","August","September","October","November","December")))

gg6<-ggplot(nmds.scores, aes(x = NMDS1, y = NMDS2)) + 
  geom_point(size = 3, aes(colour = Month)) +
  geom_encircle(aes(fill = Month), s_shape = 1, expand = 0,
                alpha = 0.2, color = "black", show.legend = FALSE) +
  theme_bw()

plot(gg6)

#Monthly, separated in Exmoor and Galloway

reads<-dataset$reads

reads<-cbind(reads, dataset@samples$source)
reads_gal<-reads[which(reads[,ncol(reads)]==3),]
reads_exm<-reads[which(reads[,ncol(reads)]==2),]

samples_gal<-samples[which(samples$source=="galloway"),]
samples_exm<-samples[which(samples$source=="exmoor"),]

#For Galloway
mreads<-as.matrix(sqrt(reads_gal))
#mreads<-as.matrix(reads) #With or without transformation?
nmds = metaMDS(mreads, distance = "bray")
nmds.scores = as.data.frame(vegan::scores(nmds))
head(nmds.scores)

nmds.scores$Sample = row.names(samples_gal)
nmds.scores$Source = samples_gal$source
nmds.scores$Habitat = samples_gal$habitat
nmds.scores$Month = samples_gal$month
nmds.scores$Season = samples_gal$season

nmds.scores<-nmds.scores %>%
  dplyr::mutate(Month=factor(Month, levels=c("January","February","March","April","May","June","July","August","September","October","November","December")))

gg7<-ggplot(nmds.scores, aes(x = NMDS1, y = NMDS2)) + 
  geom_point(size = 3, aes(colour = Month)) +
  scale_color_manual(values=c("lightskyblue1","lightskyblue3","lightgreen","palegreen4","olivedrab","orange2","darkorange3","firebrick2","burlywood4","burlywood3","tan","dodgerblue")) +
  geom_encircle(aes(fill = Month), s_shape = 1, expand = 0,
                alpha = 0.2, color = "black", show.legend = FALSE) +
  scale_fill_manual(values=c("lightskyblue1","lightskyblue3","lightgreen","palegreen4","olivedrab","orange2","darkorange3","firebrick2","burlywood4","burlywood3","tan","dodgerblue")) +
  #coord_cartesian(xlim=c(-3,2.2),ylim=c(-2.5,4)) +
  theme_bw()

plot(gg7)



#Month, galloway

#Presence/absence
reads_gal[reads_gal>0]<-1

mreads<-as.matrix(sqrt(reads_gal))
#mreads<-as.matrix(reads) #With or without transformation?
nmds = metaMDS(mreads, distance = "bray")
nmds.scores = as.data.frame(vegan::scores(nmds))
head(nmds.scores)

nmds.scores$Sample = row.names(samples_gal)
nmds.scores$Source = samples_gal$source
nmds.scores$Habitat = samples_gal$habitat
nmds.scores$Month = samples_gal$month

nmds.scores<-nmds.scores %>%
  dplyr::mutate(Month=factor(Month, levels=c("January","February","March","April","May","June","July","August","September","October","November","December")))

gg8<-ggplot(nmds.scores, aes(x = NMDS1, y = NMDS2)) + 
  geom_point(size = 3, aes(colour = Month)) +
  scale_color_manual(values=c('#e6194B', '#3cb44b', '#ffe119', '#4363d8', '#f58231', '#42d4f4', '#f032e6', '#fabed4', '#469990', '#dcbeff', '#9A6324', '#fffac8')) +
  geom_encircle(aes(fill = Month), s_shape = 1, expand = 0,
                alpha = 0.2, color = "black", show.legend = FALSE) +
  scale_fill_manual(values=c('#e6194B', '#3cb44b', '#ffe119', '#4363d8', '#f58231', '#42d4f4', '#f032e6', '#fabed4', '#469990', '#dcbeff', '#9A6324', '#fffac8')) +
  coord_cartesian(xlim=c(-1.5,1.5),ylim=c(-1.2,2)) +
  theme_bw()

plot(gg8)


#For Exmoor
mreads<-as.matrix(sqrt(reads_exm))
#mreads<-as.matrix(reads) #With or without transformation?
nmds = metaMDS(mreads, distance = "bray")
nmds.scores = as.data.frame(vegan::scores(nmds))
head(nmds.scores)

nmds.scores$Sample = row.names(samples_exm)
nmds.scores$Source = samples_exm$source
nmds.scores$Habitat = samples_exm$habitat
nmds.scores$Month = samples_exm$month

nmds.scores<-nmds.scores %>%
  dplyr::mutate(Month=factor(Month, levels=c("January","February","March","April","May","June","July","August","September","October","November","December")))

gg9<-ggplot(nmds.scores, aes(x = NMDS1, y = NMDS2)) + 
  geom_point(size = 3, aes(colour = Month)) +
  scale_color_manual(values=c("lightskyblue1","lightskyblue3","lightgreen","palegreen4","olivedrab","orange2","darkorange3","firebrick2","burlywood4","burlywood3","tan","dodgerblue")) +
  geom_encircle(aes(fill = Month), s_shape = 1, expand = 0,
                alpha = 0.2, color = "black", show.legend = FALSE) +
  scale_fill_manual(values=c("lightskyblue1","lightskyblue3","lightgreen","palegreen4","olivedrab","orange2","darkorange3","firebrick2","burlywood4","burlywood3","tan","dodgerblue")) +
  #coord_cartesian(xlim=c(-3,2.2),ylim=c(-2.5,4)) +
  theme_bw()

plot(gg9)

#Month, exmoor


#Presence/absence
reads_exm[reads_exm>0]<-1

mreads<-as.matrix(sqrt(reads_exm))
#mreads<-as.matrix(reads) #With or without transformation?
nmds = metaMDS(mreads, distance = "bray")
nmds.scores = as.data.frame(vegan::scores(nmds))
head(nmds.scores)

nmds.scores$Sample = row.names(samples_exm)
nmds.scores$Source = samples_exm$source
nmds.scores$Habitat = samples_exm$habitat
nmds.scores$Month = samples_exm$month

nmds.scores<-nmds.scores %>%
  dplyr::mutate(Month=factor(Month, levels=c("January","February","March","April","May","June","July","August","September","October","November","December")))

gg10<-ggplot(nmds.scores, aes(x = NMDS1, y = NMDS2)) + 
  geom_point(size = 3, aes(colour = Month)) +
  scale_color_manual(values=c('#e6194B', '#3cb44b', '#ffe119', '#4363d8', '#f58231', '#42d4f4', '#f032e6', '#fabed4', '#469990', '#dcbeff', '#9A6324', '#fffac8')) +
  geom_encircle(aes(fill = Month), s_shape = 1, expand = 0,
                alpha = 0.2, color = "black", show.legend = FALSE) +
  scale_fill_manual(values=c('#e6194B', '#3cb44b', '#ffe119', '#4363d8', '#f58231', '#42d4f4', '#f032e6', '#fabed4', '#469990', '#dcbeff', '#9A6324', '#fffac8')) +
  coord_cartesian(xlim=c(-3,2.2),ylim=c(-2.5,4)) +
  theme_bw()

plot(gg10)

#####For Galloway/Exmoor , open/forest

#Perform NMDS-plot of reads
reads<-dataset$reads

mreads<-as.matrix(sqrt(reads))
#mreads<-as.matrix(reads) #With or without transformation?
nmds = metaMDS(mreads, distance = "bray")
nmds.scores = as.data.frame(vegan::scores(nmds))
head(nmds.scores)

nmds.scores$Sample = row.names(samples)
nmds.scores$Source = samples$source
nmds.scores$Habitat = samples$habitat
nmds.scores$Month = samples$month
nmds.scores$Season = samples$season
nmds.scores$Group = samples$group
nmds.scores$Group2 = samples$group3


gg11<-ggplot(nmds.scores, aes(x = NMDS1, y = NMDS2)) + 
  geom_point(size = 3, aes(colour = Group2)) +
  scale_color_manual(values=c("lightpink1","red4","red2","gold2","darkorange3","darkgoldenrod")) +
  geom_encircle(aes(fill = Group2), s_shape = 1, expand = 0,
                alpha = 0.2, color = "black", show.legend = FALSE) +
  scale_fill_manual(values=c("lightpink1","red4","red2","gold2","darkorange3","darkgoldenrod")) +
  annotate("text", x=0, y=2, label="All samples - all metazoans", cex=3) +
  annotate("text", x=0, y=1.8, label="(Squareroot - transformed read counts)", cex=3) +
  theme_bw()

plot(gg11)

# https://jkzorz.github.io/2019/06/06/NMDS.html 
# https://stackoverflow.com/questions/52289812/group-geom-point-with-the-geom-polygon/52290514?fbclid=IwAR0xPB5W9fZc3dYb8868fJ_SiKgb9WPXVofZsrn-HsfJd1KEoVRkW52qQk0

#Seasonal, separated in Exmoor and Galloway

reads<-dataset$reads

#For Galloway
mreads<-as.matrix(sqrt(reads))
#mreads<-as.matrix(reads) #With or without transformation?
nmds = metaMDS(mreads, distance = "bray")
nmds.scores = as.data.frame(vegan::scores(nmds))
head(nmds.scores)

nmds.scores$Sample = row.names(samples)
nmds.scores$Source = samples$source
nmds.scores$Habitat = samples$habitat
nmds.scores$Month = samples$month
nmds.scores$Season = samples$season

nmds.scores<-nmds.scores %>%
  dplyr::mutate(Season=factor(Season, levels=c("early","mid","late")))

gg12<-ggplot(nmds.scores[which(nmds.scores$Source=="galloway"),], aes(x = NMDS1, y = NMDS2)) + 
  geom_point(size = 3, aes(colour = Season)) +
  scale_color_manual(values=c("gold2","darkorange3","darkgoldenrod")) +
  geom_encircle(aes(fill = Season), s_shape = 1, expand = 0,
                alpha = 0.2, color = "black", show.legend = FALSE) +
  scale_fill_manual(values=c("gold2","darkorange3","darkgoldenrod")) +
  coord_cartesian(xlim=c(-2,1.8),ylim=c(-1.5,2)) +
  annotate("text", x=0, y=2, label="Galloway samples - all metazoans", cex=3) +
  annotate("text", x=0, y=1.8, label="(Squareroot - transformed read counts)", cex=3) +
  theme_bw()

plot(gg12)




#For Exmoor
mreads<-as.matrix(sqrt(reads))
#mreads<-as.matrix(reads) #With or without transformation?
nmds = metaMDS(mreads, distance = "bray")
nmds.scores = as.data.frame(vegan::scores(nmds))
head(nmds.scores)

nmds.scores$Sample = row.names(samples)
nmds.scores$Source = samples$source
nmds.scores$Habitat = samples$habitat
nmds.scores$Month = samples$month
nmds.scores$Season = samples$season

nmds.scores<-nmds.scores %>%
  dplyr::mutate(Season=factor(Season, levels=c("early","mid","late")))

gg13<-ggplot(nmds.scores[which(nmds.scores$Source=="exmoor"),], aes(x = NMDS1, y = NMDS2)) + 
  geom_point(size = 3, aes(colour = Season)) +
  scale_color_manual(values=c("lightpink1","red4","red2")) +
  geom_encircle(aes(fill = Season), s_shape = 1, expand = 0,
                alpha = 0.2, color = "black", show.legend = FALSE) +
  scale_fill_manual(values=c("lightpink1","red4","red2")) +
  coord_cartesian(xlim=c(-2,1.8),ylim=c(-1.5,2)) +
  annotate("text", x=0, y=2, label="Exmoor samples - all metazoans", cex=3) +
  annotate("text", x=0, y=1.8, label="(Squareroot - transformed read counts)", cex=3) +
  theme_bw()

plot(gg13)


######## FINAL - seasonal by source and habitat


reads<-dataset$reads

#For Galloway
mreads<-as.matrix(sqrt(reads))
#mreads<-as.matrix(reads) #With or without transformation?
nmds = metaMDS(mreads, distance = "bray")
nmds.scores = as.data.frame(vegan::scores(nmds))
head(nmds.scores)

nmds.scores$Sample = row.names(samples)
nmds.scores$Source = samples$source
nmds.scores$Habitat = samples$habitat
nmds.scores$Month = samples$month
nmds.scores$Season = samples$season

nmds.scores<-nmds.scores %>%
  dplyr::mutate(Season=factor(Season, levels=c("early","mid","late")))

gg14<-ggplot(nmds.scores[which(nmds.scores$Source=="galloway" & nmds.scores$Habitat=="open"),], aes(x = NMDS1, y = NMDS2)) + 
  geom_point(size = 3, aes(colour = Season)) +
  scale_color_manual(values=c("coral1","sandybrown","sienna")) +
  geom_encircle(aes(fill = Season), s_shape = 1, expand = 0,
                alpha = 0.2, color = "black", show.legend = FALSE) +
  scale_fill_manual(values=c("coral1","sandybrown","sienna")) +
  annotate("text", x=-1.5, y=-1.5, label="Galloway - Open", cex=3) +
  #coord_cartesian(xlim=c(-3,2.2),ylim=c(-2.5,4)) +
  theme_bw()

plot(gg14)

#gg14<-gg14 + theme(legend.position="none")


gg15<-ggplot(nmds.scores[which(nmds.scores$Source=="galloway" & nmds.scores$Habitat=="forest"),], aes(x = NMDS1, y = NMDS2)) + 
  geom_point(size = 3, aes(colour = Season)) +
  scale_color_manual(values=c("coral1","sandybrown","sienna")) +
  geom_encircle(aes(fill = Season), s_shape = 1, expand = 0,
                alpha = 0.2, color = "black", show.legend = FALSE) +
  scale_fill_manual(values=c("coral1","sandybrown","sienna")) +
  annotate("text", x=-1.5, y=3.5, label="Galloway - Forest", cex=3) +
  #coord_cartesian(xlim=c(-3,2.2),ylim=c(-2.5,4)) +
  theme_bw()

plot(gg15)


gg16<-ggplot(nmds.scores[which(nmds.scores$Source=="exmoor" & nmds.scores$Habitat=="open"),], aes(x = NMDS1, y = NMDS2)) + 
  geom_point(size = 3, aes(colour = Season)) +
  scale_color_manual(values=c("lightpink","firebrick2","hotpink4")) +
  geom_encircle(aes(fill = Season), s_shape = 1, expand = 0,
                alpha = 0.2, color = "black", show.legend = FALSE) +
  scale_fill_manual(values=c("lightpink","firebrick2","hotpink4")) +
  annotate("text", x=1.5, y=-1.5, label="Exmoor - Open", cex=3) +
  #coord_cartesian(xlim=c(-3,2.2),ylim=c(-2.5,4)) +
  theme_bw()

plot(gg16)

#gg16<-gg16 + theme(legend.position="none")

gg17<-ggplot(nmds.scores[which(nmds.scores$Source=="exmoor" & nmds.scores$Habitat=="forest"),], aes(x = NMDS1, y = NMDS2)) + 
  geom_point(size = 3, aes(colour = Season)) +
  scale_color_manual(values=c("lightpink","firebrick2","hotpink4")) +
  geom_encircle(aes(fill = Season), s_shape = 1, expand = 0,
                alpha = 0.2, color = "black", show.legend = FALSE) +
  scale_fill_manual(values=c("lightpink","firebrick2","hotpink4")) +
  annotate("text", x=-1.5, y=1.5, label="Exmoor - Forest", cex=3) +
  #coord_cartesian(xlim=c(-3,2.2),ylim=c(-2.5,4)) +
  theme_bw()

plot(gg17)

ggarrange(gg1,gg3,gg12,gg13, labels = c("A", "B","C","D"), ncol = 2, nrow = 2)
ggsave("COI/Local_analysis/output/plots/nMDS_COI_all.pdf", width=10, height=8)

ggarrange(gg1,gg3,gg11, labels = c("A", "B","C"), ncol = 3, nrow = 1)
ggsave("COI/Local_analysis/output/plots/nMDS_COI_all_2.pdf", width=16, height=4)





#PERMANOVA

#Galloway vs. Exmoor
dist<-vegdist(mreads, method = "bray")

##Test for homogeneity of multivariate variance
#Galloway vs. exmoor
dispersion <- betadisper(dist, group=samples$group)
permutest(dispersion)

#No homogeneity of dispersion between groups, square root transformation applied
dist.t<-sqrt(dist)
dispersion <- betadisper(dist.t, group=samples$group)
permutest(dispersion)




plot(dispersion, hull=FALSE, ellipse=TRUE) ##sd ellipse

perm<-adonis2(dist~source+season+habitat, data=samples, permutations = 999)
perm





#Create RDS with p.values from PERMANOVA

perm.out<-perm

saveRDS(perm.out, file="COI/Local_analysis/output/RDS_files/permanova_output_all")

write.table(perm.out, file="COI/Local_analysis/output/textfiles/permanova_output_COI_all.txt", sep="\t",row.names = TRUE, col.names = TRUE)


```

```{r Model richness}

df<-readRDS("COI/Local_analysis/output/RDS_files/Richness_df_all")

month_vec=c()
for (i in 1:nrow(df)) {
  if (df$month[i]=="January") {month_vec<-append(month_vec,1)} 
  else if (df$month[i]=="February") {month_vec<-append(month_vec,2)} 
  else if (df$month[i]=="March") {month_vec<-append(month_vec,3)}
  else if (df$month[i]=="April") {month_vec<-append(month_vec,4)}
  else if (df$month[i]=="May") {month_vec<-append(month_vec,5)}
  else if (df$month[i]=="June") {month_vec<-append(month_vec,6)}
  else if (df$month[i]=="July") {month_vec<-append(month_vec,7)}
  else if (df$month[i]=="August") {month_vec<-append(month_vec,8)}
  else if (df$month[i]=="September") {month_vec<-append(month_vec,9)}
  else if (df$month[i]=="October") {month_vec<-append(month_vec,10)}
  else if (df$month[i]=="November") {month_vec<-append(month_vec,11)}
  else if (df$month[i]=="December") {month_vec<-append(month_vec,12)}
  
}
season_vec=c()
for (i in 1:nrow(df)) {
  if (df$month[i]=="January") {season_vec<-append(season_vec,"early")} 
  else if (df$month[i]=="February") {season_vec<-append(season_vec,"early")} 
  else if (df$month[i]=="March") {season_vec<-append(season_vec,"early")}
  else if (df$month[i]=="April") {season_vec<-append(season_vec,"early")}
  else if (df$month[i]=="May") {season_vec<-append(season_vec,"mid")}
  else if (df$month[i]=="June") {season_vec<-append(season_vec,"mid")}
  else if (df$month[i]=="July") {season_vec<-append(season_vec,"mid")}
  else if (df$month[i]=="August") {season_vec<-append(season_vec,"mid")}
  else if (df$month[i]=="September") {season_vec<-append(season_vec,"late")}
  else if (df$month[i]=="October") {season_vec<-append(season_vec,"late")}
  else if (df$month[i]=="November") {season_vec<-append(season_vec,"late")}
  else if (df$month[i]=="December") {season_vec<-append(season_vec,"late")}
  
}

df<-cbind(df, "season"=as.factor(season_vec))

levels(df$source)<-droplevels(df$source,"control")

hist(df$Count)

model1.1<-glm(Count~season+source+habitat, family="poisson",data=df)
summary(model1.1)

plot(model1.1)

redu1<-glm(Count~source, family="poisson",data=df)

redu2<-glm(Count~season, family="poisson",data=df)

redu3<-glm(Count~habitat, family="poisson",data=df)

redu4<-glm(Count~source+season,family="poisson",data=df)

redu5<-glm(Count~source+habitat, family="poisson",data=df)

redu6<-glm(Count~habitat+season, family="poisson",data=df)

comparison<-anova(model1.1,redu1,redu2,redu3,redu4,redu5,redu6)

library(MASS)
library(spdep)
selection<-MASS::stepAIC(model1.1)
selection

colors = c("red","blue","green")

par(mfrow=c(2,2))
boxplot(Count~source+habitat+season, data=df, col=colors)
boxplot(Count~source, data=df, col=colors)
boxplot(Count~habitat, data=df, col=colors)
boxplot(Count~season+source, data=df, col=colors)

#df_gal<-subset(df, df$source=="galloway")
#df_exm<-subset(df, df$source=="exmoor")


#adding a spatial structure
#Spatial autocorrelation
#See mixed effects model II slides


#Correlograms by spline.correlog

#par(mfrow = c(1, 2), mar = c(5, 5, 2, 0.1))
## Plot correlogram 
#Splcor.SR <- spline.correlog(
#  x = df$lon, y = df$lat, z = df$Count,
#  latlon = T, na.rm = T, npoints = 1000, resamp = 1000, quiet = TRUE
#)
#plot(Splcor.SR, main = "Genera richness", cex = 1.5)
## Plot correlogram of model.3 residuals using the spline.correlog function
#Splcor.model1.1 <- spline.correlog(
#  x = df$lon, y = df$lat, z = residuals(model1.1),
#  latlon = T, na.rm = T, npoints = 1000, resamp = 1000, quiet = TRUE
#)
#plot(Splcor.model1.1, main = "Model1.1 model residuals", cex = 1.5)


#Estimating Moran's I

#m <- knearneigh(as.matrix(df[, c("lon", "lat")]), k = 1, longlat = TRUE)
#n <- knn2nb(m)
#ww <- nb2listw(n, zero.policy = TRUE)
#moran <- moran(df$Count, ww, n = length(ww$neighbours), S0 = Szero(ww))


#Moran.mc <- moran.mc(df$Count, listw = ww, nsim=1000)
#Moran.mc$p.value



## SAR-error model

#m <- knearneigh(as.matrix(df[, c("lon", "lat")]), k = 1, longlat = TRUE)
#n <- knn2nb(m)
#ww <- nb2listw(n, zero.policy = TRUE)
#SAR.Error <- errorsarlm(Count ~ source*month_number, listw = ww, data = df)

#coef(SAR.Error)
#coef(model1.2)

##Spline corellograms

#par(mfrow = c(1, 2), mar = c(5, 5, 2, 0.1))
#Splcor.model1.2 <- spline.correlog(
#  x = df$lon, y = df$lat,
#  z = residuals(model1.2),
#  latlon = TRUE, na.rm = TRUE,
#  npoints = 1000, resamp = 1000,
#  quiet = TRUE
#)
#plot(Splcor.model1.2, main = "Model1.2 model residuals", cex = 1.5)

#Splcor.SAR <- spline.correlog(
#  x = df$lon, y = df$lat,
#  z = residuals(SAR.Error),
#  latlon = TRUE, na.rm = TRUE,
#  npoints = 1000, resamp = 1000,
#  quiet = TRUE
#)
#plot(Splcor.SAR, main = "SAR model residuals", cex = 1.5)


#summary(SAR.Error)

##### DIET RICHNESS #############################################################################

#Test for difference in diet richness between galloway and exmoor in each season
t1<-kruskal.test(Count~source,data=df)
t2<-kruskal.test(Count~season,data=df)
t3<-kruskal.test(Count~habitat,data=df)

RG<-c(mean(df$Count[which(df$source=="galloway")]), std.error(df$Count[which(df$source=="galloway")]))
REx<-c(mean(df$Count[which(df$source=="exmoor")]), std.error(df$Count[which(df$source=="exmoor")]))
RO<-c(mean(df$Count[which(df$habitat=="open")]), std.error(df$Count[which(df$habitat=="open")]))
RF<-c(mean(df$Count[which(df$habitat=="forest")]), std.error(df$Count[which(df$habitat=="forest")]))

## Differences between sources
#Early
t4<-wilcox.test(df$Count[which(df$season=="early" & df$source=="galloway")],df$Count[which(df$season=="early" & df$source=="exmoor")])
# no difference
#Mid
t5<-wilcox.test(df$Count[which(df$season=="mid" & df$source=="galloway")],df$Count[which(df$season=="mid" & df$source=="exmoor")])
#marginally, but prob. not after corrections
#Late
t6<-wilcox.test(df$Count[which(df$season=="late" & df$source=="galloway")],df$Count[which(df$season=="late" & df$source=="exmoor")])
#yes, but prob. not after corrections
# MEANS and sd. err
RGE<-c(mean(df$Count[which(df$season=="early" & df$source=="galloway")]), std.error(df$Count[which(df$season=="early" & df$source=="galloway")]))
RGM<-c(mean(df$Count[which(df$season=="mid" & df$source=="galloway")]), std.error(df$Count[which(df$season=="mid" & df$source=="galloway")]))
RGL<-c(mean(df$Count[which(df$season=="late" & df$source=="galloway")]), std.error(df$Count[which(df$season=="late" & df$source=="galloway")]))
REE<-c(mean(df$Count[which(df$season=="early" & df$source=="exmoor")]), std.error(df$Count[which(df$season=="early" & df$source=="exmoor")]))
REM<-c(mean(df$Count[which(df$season=="mid" & df$source=="exmoor")]), std.error(df$Count[which(df$season=="mid" & df$source=="exmoor")]))
REL<-c(mean(df$Count[which(df$season=="late" & df$source=="exmoor")]), std.error(df$Count[which(df$season=="late" & df$source=="exmoor")]))

## Differences between seasons
#Galloway
t7<-wilcox.test(df$Count[which(df$season=="early" & df$source=="galloway")],df$Count[which(df$season=="mid" & df$source=="galloway")])
t8<-wilcox.test(df$Count[which(df$season=="early" & df$source=="galloway")],df$Count[which(df$season=="late" & df$source=="galloway")])
t9<-wilcox.test(df$Count[which(df$season=="late" & df$source=="galloway")],df$Count[which(df$season=="mid" & df$source=="galloway")])

#Exmoor
t10<-wilcox.test(df$Count[which(df$season=="early" & df$source=="exmoor")],df$Count[which(df$season=="mid" & df$source=="exmoor")])
t11<-wilcox.test(df$Count[which(df$season=="early" & df$source=="exmoor")],df$Count[which(df$season=="late" & df$source=="exmoor")])
t12<-wilcox.test(df$Count[which(df$season=="late" & df$source=="exmoor")],df$Count[which(df$season=="mid" & df$source=="exmoor")])

#All
t13<-wilcox.test(df$Count[which(df$season=="early")],df$Count[which(df$season=="mid")])
t14<-wilcox.test(df$Count[which(df$season=="early")],df$Count[which(df$season=="late")])
t15<-wilcox.test(df$Count[which(df$season=="late")],df$Count[which(df$season=="mid")])


#Open vs. forest, each source
t16<-wilcox.test(df$Count[which(df$habitat=="open" & df$source=="galloway")],df$Count[which(df$habitat=="forest" & df$source=="galloway")])
t17<-wilcox.test(df$Count[which(df$habitat=="open" & df$source=="exmoor")],df$Count[which(df$habitat=="forest" & df$source=="exmoor")])

#Means and sd. err.
RE<-c(mean(df$Count[which(df$season=="early")]), std.error(df$Count[which(df$season=="early")]))
RM<-c(mean(df$Count[which(df$season=="mid")]), std.error(df$Count[which(df$season=="mid")]))
RL<-c(mean(df$Count[which(df$season=="late")]), std.error(df$Count[which(df$season=="late")]))

RGO<-c(mean(df$Count[which(df$habitat=="open" & df$source=="galloway")]), std.error(df$Count[which(df$habitat=="open" & df$source=="galloway")]))
RGF<-c(mean(df$Count[which(df$habitat=="forest" & df$source=="galloway")]), std.error(df$Count[which(df$habitat=="forest" & df$source=="galloway")]))
REO<-c(mean(df$Count[which(df$habitat=="open" & df$source=="exmoor")]), std.error(df$Count[which(df$habitat=="open" & df$source=="exmoor")]))
REF<-c(mean(df$Count[which(df$habitat=="forest" & df$source=="exmoor")]), std.error(df$Count[which(df$habitat=="forest" & df$source=="exmoor")]))

pvals<-data.frame(c(t1$p.value,t2$p.value,t3$p.value,t4$p.value,t5$p.value,t6$p.value,t7$p.value,t8$p.value,t9$p.value,t10$p.value,t11$p.value,t12$p.value,t13$p.value,t14$p.value,t15$p.value,t16$p.value,t17$p.value))
rownames(pvals)<-c("t1","t2","t3","t4","t5","t6","t7","t8","t9","t10","t11","t12","t13","t14","t15","t16","t17")
colnames(pvals)<-"p.value"

holm<-p.adjust(pvals$p.value, method="holm")
pvals<-cbind(pvals,"corrected"=holm)


significant<-c()
for (i in 1:nrow(pvals)) {
  if (pvals$corrected[i]<0.01) {significant<-append(significant, "yes")}
  else if (pvals$corrected[i]<0.05 && pvals$corrected[i]>0.01) {significant<-append(significant, "marginally")}
  else {significant<-append(significant, "no")}
}
pvals<-cbind(pvals, significant)

saveRDS(pvals, "COI/Local_analysis/output/RDS_files/pvals_difference_all")
write.table(pvals,"COI/Local_analysis/output/tables/pvals_difference_all.txt",sep="\t",row.names=TRUE)

means<-c("mean"=c(),"StERR"=c())
means<-rbind(means,RGE,RGM,RGL,REE,REM,REL,RE,RM,RL,RG,REx,RO,RF,RGO,RGF,REO,REF)
colnames(means)<-c("mean","StErr")

saveRDS(means, "COI/Local_analysis/output/RDS_files/means_groups_all")
write.table(means,"COI/Local_analysis/output/tables/means_groups_all.txt",sep="\t",row.names=TRUE)



```

```{r Genera accumulation for each month, warning=FALSE}

no.rare<-readRDS("COI/Local_analysis/output/RDS_files/dataset_after_aggregation")

#Arthropods only
#no.rare<-readRDS("COI/Local_analysis/output/RDS_files/dataset_final_arthropods")


  month=merge(no.rare@reads,no.rare@samples[, c("month", "name","source","habitat")],by="row.names")
  month2=within(month,rm("name","Row.names"))
  
  #month_gal<-month2[which(month2$source=="galloway" & month2$habitat=="open"),]
  month_gal<-month2[which(month2$source=="galloway"),]
  month_gal=within(month_gal,rm("source","habitat"))
  
  colnames(month_gal)[1:length(no.rare@motus$final.otu)]<-no.rare@motus$final.otu
  
  month_gal[month_gal>0]<-1
  
  ##Remove unidentified diptera, chromadorea & strongylida
  month_gal<-month_gal[,which(!grepl("Chromadorea",colnames(month_gal)))]
  month_gal<-month_gal[,which(!grepl("Diptera",colnames(month_gal)))]
  month_gal<-month_gal[,which(!grepl("Strongylida",colnames(month_gal)))]
  
  
  ##Remove empty columns
  month_gal<-month_gal[, colSums(month_gal != 0) > 0]
  n=ncol(month_gal)-1
  
    par(mfrow=c(4,3))
  par(mar=c(4,3,2,1))

    for (i in unique(month_gal$month)) {
    subset<-subset(month_gal,month==i)
    plot(specaccum(subset[1:n],method="exact"), ci.type="poly", col="blue", lwd=2, ci.lty=0,   ci.col="lightblue",xlab="",ylab="",xaxt="n",yaxt="n",main=unique(subset$month))
    axis(1,at=c(1:10))
    axis(2,at=c(25,50,75,100,125))
    }

    warnings()

    

```
