---
title: "Create plots"
author: "Emil Ellegaard Thomassen"
date: "`r Sys.Date()"
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r Setup and load packages}
knitr::opts_chunk$set(
	echo = TRUE,
	fig.height = 5.5,
	message = FALSE,
	warning = FALSE,
	autodep = TRUE,
	cache = TRUE,
	cache.lazy = FALSE,
	tidy = TRUE,
	tidy.opts = list(width.cutoff = 80)
)
rm(list=ls())
gc()
Dir.Base <- here::here()



# Installing packages as needed
install.load.package <- function(x) {
  if (!require(x, character.only = TRUE))
    install.packages(x, repos='http://cran.us.r-project.org', dependencies = TRUE)
  require(x, character.only = TRUE)
}
package_vec <- c("kableExtra", "tidyverse","png", "jpeg", "sp", "ncf","rgdal","MASS", "raster", "ggmap", "ggplot2", "BiodiversityR", "pheatmap", "knitr", "printr", "ade4", "vegan", "ROBITools", "ROBITaxonomy", "dplyr", "tidyr", "plotrix","ggpubr")
sapply(package_vec, install.load.package)

knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, cache = TRUE, cache.lazy=FALSE, tidy.opts=list(width.cutoff=80),tidy=TRUE, fig.height=5.5)
options(digits=4, width = 90)

```


```{r Species richness plots}

level_order <- c("January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December") 

img_all<-readPNG("COI/Local_analysis/external_figures/all_dung-ass.png", native=TRUE) 
img_cole<-readPNG("COI/Local_analysis/external_figures/beetle.png", native=TRUE) 
img_dip<-readPNG("COI/Local_analysis/external_figures/fly.png", native=TRUE) 
img_nema<-readPNG("COI/Local_analysis/external_figures/nematode.png", native=TRUE) 

#All 
SR_all<-readRDS(file="COI/Local_analysis/output/RDS_files/Species_Richness")
SR_all<-SR_all + ggtitle("All metazoans") 

#Nematodes
SR_nema<-readRDS(file="COI/Local_analysis/output/RDS_files/Species_Richness_nematodes")
SR_nema<-SR_nema + ggtitle("Nematodes") + annotation_raster(img_nema,1,3,12,16)
SR_nema <- SR_nema +  theme(text = element_text(size = 14))

#Dung-associated arthropods
SR_dung<-readRDS(file="COI/Local_analysis/output/RDS_files/Species_Richness_arthropods")
SR_dung<-SR_dung + ggtitle("Dung-associated arthropods") + annotation_raster(img_all,1,3.5,14,22)
SR_dung <- SR_dung +  theme(text = element_text(size = 14))

#Coleoptera
SR_cole<-readRDS(file="COI/Local_analysis/output/RDS_files/Species_Richness_coleoptera")
SR_cole<-SR_cole + ggtitle("Dung-associated beetles") + annotation_raster(img_cole,1,3,4.5,7)
SR_cole <- SR_cole +  theme(text = element_text(size = 14))


#Diptera
SR_dip<-readRDS(file="COI/Local_analysis/output/RDS_files/Species_Richness_diptera")
SR_dip<-SR_dip + ggtitle("Dung-associated flies and allies") + annotation_raster(img_dip,1,3,7,11)
SR_dip <- SR_dip +  theme(text = element_text(size = 14))

#Plants
SR_plants<-readRDS(file="ITS/Local_analysis/output/RDS_files/Species_Richness_genera")
SR_plants<-SR_plants + ggtitle("Plant diet")

#Fungi
SR_fungi<-readRDS(file="ITS/Local_analysis/output/RDS_files/Species_Richness_fungi")
SR_fungi<-SR_fungi + ggtitle("Fungi")

ggarrange(SR_dung, SR_cole, SR_dip, SR_nema, labels = c("A","B","C","D"), nrow = 2,ncol=2)
ggsave("COI/Local_analysis/output/figures/richness_plots_main_vers_26_01_23.png", width=15, height=10)

  
```


```{r Stacked barplots}


Cole_gal<-readRDS(file="COI/Local_analysis/output/RDS_files/stacked_gal_months_coleoptera")
Cole_gal<- Cole_gal + ggtitle("Galloway - coleoptera")
Cole_exm<-readRDS(file="COI/Local_analysis/output/RDS_files/stacked_exm_months_coleoptera")
Cole_exm<- Cole_exm + ggtitle("Exmoor - coleoptera")
Dip_gal<-readRDS(file="COI/Local_analysis/output/RDS_files/stacked_gal_months_diptera")
Dip_gal<- Dip_gal + ggtitle("Galloway - diptera")
Dip_exm<-readRDS(file="COI/Local_analysis/output/RDS_files/stacked_exm_months_diptera")
Dip_exm<- Dip_exm + ggtitle("Exmoor - diptera")

ggarrange(Cole_gal,Cole_exm,Dip_gal,Dip_exm, labels = c("A","B","C","D"), nrow = 4,ncol=1)
ggsave("COI/Local_analysis/output/figures/stacked_barplots.pdf", width=10, height=16)


Cole_gal_func<-readRDS(file="COI/Local_analysis/output/RDS_files/stacked_gal_months_coleoptera_func")
Cole_gal_func<- Cole_gal_func + ggtitle("Galloway - coleoptera, functional types")
Cole_exm_func<-readRDS(file="COI/Local_analysis/output/RDS_files/stacked_exm_months_coleoptera_func")
Cole_exm_func<- Cole_exm_func + ggtitle("Exmoor - coleoptera, functional types")
Dip_gal_func<-readRDS(file="COI/Local_analysis/output/RDS_files/stacked_gal_months_diptera_func")
Dip_gal_func<- Dip_gal_func + ggtitle("Galloway - diptera, functional types")
Dip_exm_func<-readRDS(file="COI/Local_analysis/output/RDS_files/stacked_exm_months_diptera_func")
Dip_exm_func<- Dip_exm_func + ggtitle("Exmoor - diptera, functional types")

ggarrange(Cole_gal_func,Cole_exm_func,Dip_gal_func,Dip_exm_func, labels = c("A","B","C","D"), nrow = 4,ncol=1)
ggsave("COI/Local_analysis/output/figures/stacked_barplots_functional_types.png", width=14, height=16)




cole_sample<-readRDS(file="COI/Local_analysis/output/RDS_files/StackedBothSpecies_coleoptera") #A, B

cole_month<-readRDS(file="COI/Local_analysis/output/RDS_files/StackedBothMonthsSpecies_coleoptera") #A, B

dip_sample<-readRDS(file="COI/Local_analysis/output/RDS_files/StackedBothSpecies_diptera")       # C, D

dip_month<-readRDS(file="COI/Local_analysis/output/RDS_files/StackedBothMonthsSpecies_diptera")        # C, D

nema_sample<-readRDS(file="COI/Local_analysis/output/RDS_files/StackedBothSpecies_nematodes")      # E, F

nema_month<-readRDS(file="COI/Local_analysis/output/RDS_files/StackedBothMonthsSpecies_nematodes")       # E, F

fungi_sample<-readRDS(file="ITS/Local_analysis/output/RDS_files/StackedBothSpecies_fungi")    # G, H

fungi_month<-readRDS(file="ITS/Local_analysis/output/RDS_files/StackedBothMonthSpecies_fungi")      # G, H


ggarrange(cole_month,dip_month, labels=c(""), nrow=2, ncol=1)
ggsave("COI/Local_analysis/output/figures/stacked_barplots_month_cole_dip.png", width=18, height=24)

ggarrange(nema_month,fungi_month, labels=c(""), nrow=2, ncol=1)
ggsave("COI/Local_analysis/output/figures/stacked_barplots_month_nema_fungi.png", width=18, height=24)

ggarrange(cole_sample,dip_sample, labels=c(""), nrow=2, ncol=1)
ggsave("COI/Local_analysis/output/figures/stacked_barplots_sample_cole_dip.png", width=18, height=24)

ggarrange(nema_sample,fungi_sample, labels=c(""), nrow=2, ncol=1)
ggsave("COI/Local_analysis/output/figures/stacked_barplots_sample_nema_fungi.png", width=18, height=24)


```

```{r Plant richness and ordination}


level_order <- c("January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December") 


#Plants
SR_plants<-readRDS(file="ITS/Local_analysis/output/RDS_files/Species_Richness_genera")

NMDS_plants<-readRDS(file="ITS/Local_analysis/output/RDS_files/nMDS_plants")

NMDS_plants2<-readRDS(file="ITS/Local_analysis/output/RDS_files/nMDS_plants2")
NMDS_plants2<-NMDS_plants2 + theme(legend.text = element_text(size = 24)) 

ggarrange(SR_plants,NMDS_plants, labels = c("A",""), nrow = 2,ncol=1)

ggsave("ITS/Local_analysis/output/figures/richness_nmds_plot.pdf", width=10, height=7)


ggarrange(SR_plants,NMDS_plants,NMDS_plants2, labels = c("A","",""), nrow = 3,ncol=1)

ggsave("ITS/Local_analysis/output/figures/richness_nmds_plot_vers2.png", width=12, height=12)

```

```{r NMDS-Venn plots biodiversity}
i=20

A1<-readRDS(file="COI/Local_analysis/output/RDS_files/ggArthroGalExm")
A1<-A1 + theme(tex=element_text(size=i))
A2<-readRDS(file="COI/Local_analysis/output/RDS_files/ggArthroOpenForest")
A2<-A2 + theme(tex=element_text(size=i))
A3<-readRDS(file="COI/Local_analysis/output/RDS_files/ggArthroGalSeason")
A3<-A3 + theme(tex=element_text(size=i))
A4<-readRDS(file="COI/Local_analysis/output/RDS_files/ggArthroExmSeason")
A4<-A4 + theme(tex=element_text(size=i))

A5<-readRDS(file="COI/Local_analysis/output/RDS_files/venn1_arthropods")
A6<-readRDS(file="COI/Local_analysis/output/RDS_files/venn2_arthropods")
A7<-readRDS(file="COI/Local_analysis/output/RDS_files/venn4_arthropods")
A8<-readRDS(file="COI/Local_analysis/output/RDS_files/venn5_arthropods")

B1<-readRDS(file="COI/Local_analysis/output/RDS_files/ggColeoGalExm")
B1<-B1 + theme(tex=element_text(size=i))
B2<-readRDS(file="COI/Local_analysis/output/RDS_files/ggColeOpenForest")
B2<-B2 + theme(tex=element_text(size=i))
B3<-readRDS(file="COI/Local_analysis/output/RDS_files/ggColeGalSeason")
B3<-B3 + theme(tex=element_text(size=i))
B4<-readRDS(file="COI/Local_analysis/output/RDS_files/ggColeExmSeason")
B4<-B4 + theme(tex=element_text(size=i))

B5<-readRDS(file="COI/Local_analysis/output/RDS_files/venn1_coleoptera")
B6<-readRDS(file="COI/Local_analysis/output/RDS_files/venn2_coleoptera")
B7<-readRDS(file="COI/Local_analysis/output/RDS_files/venn4_coleoptera")
B8<-readRDS(file="COI/Local_analysis/output/RDS_files/venn5_coleoptera")

C1<-readRDS(file="COI/Local_analysis/output/RDS_files/ggDipGalExm")
C1<-C1 + theme(tex=element_text(size=i))
C2<-readRDS(file="COI/Local_analysis/output/RDS_files/ggDipOpenForest")
C2<-C2 + theme(tex=element_text(size=i))
C3<-readRDS(file="COI/Local_analysis/output/RDS_files/ggDipGalSeason")
C3<-C3 + theme(tex=element_text(size=i))
C4<-readRDS(file="COI/Local_analysis/output/RDS_files/ggDipExmSeason")
C4<-C4 + theme(tex=element_text(size=i))

C5<-readRDS(file="COI/Local_analysis/output/RDS_files/venn1_diptera")
C6<-readRDS(file="COI/Local_analysis/output/RDS_files/venn2_diptera")
C7<-readRDS(file="COI/Local_analysis/output/RDS_files/venn4_diptera")
C8<-readRDS(file="COI/Local_analysis/output/RDS_files/venn5_diptera")

D1<-readRDS(file="COI/Local_analysis/output/RDS_files/ggNemaGalExm")
D1<-D1 + theme(tex=element_text(size=i))
D2<-readRDS(file="COI/Local_analysis/output/RDS_files/ggNemaOpenForest")
D2<-D2 + theme(tex=element_text(size=i))
D3<-readRDS(file="COI/Local_analysis/output/RDS_files/ggNemaGalSeason")
D3<-D3 + theme(tex=element_text(size=i))
D4<-readRDS(file="COI/Local_analysis/output/RDS_files/ggNemaExmSeason")
D4<-D4 + theme(tex=element_text(size=i))

D5<-readRDS(file="COI/Local_analysis/output/RDS_files/venn1_nematodes")
D6<-readRDS(file="COI/Local_analysis/output/RDS_files/venn2_nematodes")
D7<-readRDS(file="COI/Local_analysis/output/RDS_files/venn4_nematodes")
D8<-readRDS(file="COI/Local_analysis/output/RDS_files/venn5_nematodes")





g1<-ggarrange(A1,A2,A3,A4, labels=c("A1","A2","A3","A4"), nrow=1, ncol=4, common.legend = FALSE)
g2<-ggarrange(A5,A6,A7,A8, labels=c("A5","A6","A7","A8"), nrow=1, ncol=4, common.legend = FALSE)
g3<-ggarrange(B1,B2,B3,B4, labels=c("B1","B2","B3","B4"), nrow=1, ncol=4, common.legend = FALSE)
g4<-ggarrange(B5,B6,B7,B8, labels=c("B5","B6","B7","B8"), nrow=1, ncol=4, common.legend = FALSE)
g5<-ggarrange(C1,C2,C3,C4, labels=c("C1","C2","C3","C4"), nrow=1, ncol=4, common.legend = FALSE)
g6<-ggarrange(C5,C6,C7,C8, labels=c("C5","C6","C7","C8"), nrow=1, ncol=4, common.legend = FALSE)
g7<-ggarrange(D1,D2,D3,D4, labels=c("D1","D2","D3","D4"), nrow=1, ncol=4, common.legend = FALSE)
g8<-ggarrange(D5,D6,D7,D8, labels=c("D5","D6","D7","D8"), nrow=1, ncol=4, common.legend = FALSE)


ggarrange(g1,g2,g3,g4,g5,g6,g7,g8, ncol = 1, nrow = 8)
ggsave("COI/Local_analysis/output/figures/NMDS_venn_biodiversity_vers1.png",height = 25, width = 20)



```

```{r NMDS-Venn biodiversity - cole_dip}

A<-readRDS(file="COI/Local_analysis/output/RDS_files/ggColeoGalExm")
B<-readRDS(file="COI/Local_analysis/output/RDS_files/ggColeOpenForest")
C<-readRDS(file="COI/Local_analysis/output/RDS_files/ggColeGalSeason")
D<-readRDS(file="COI/Local_analysis/output/RDS_files/ggColeExmSeason")

E<-readRDS(file="COI/Local_analysis/output/RDS_files/venn1_coleoptera")
F<-readRDS(file="COI/Local_analysis/output/RDS_files/venn2_coleoptera")
G<-readRDS(file="COI/Local_analysis/output/RDS_files/venn4_coleoptera")
H<-readRDS(file="COI/Local_analysis/output/RDS_files/venn5_coleoptera")

I<-readRDS(file="COI/Local_analysis/output/RDS_files/ggDipGalExm")
J<-readRDS(file="COI/Local_analysis/output/RDS_files/ggDipOpenForest")
K<-readRDS(file="COI/Local_analysis/output/RDS_files/ggDipGalSeason")
L<-readRDS(file="COI/Local_analysis/output/RDS_files/ggDipExmSeason")

M<-readRDS(file="COI/Local_analysis/output/RDS_files/venn1_diptera")
N<-readRDS(file="COI/Local_analysis/output/RDS_files/venn2_diptera")
O<-readRDS(file="COI/Local_analysis/output/RDS_files/venn4_diptera")
P<-readRDS(file="COI/Local_analysis/output/RDS_files/venn5_diptera")




g1<-ggarrange(A,B,C,D, labels=c("A","B","C","D"), nrow=1, ncol=4, common.legend = FALSE)
g2<-ggarrange(E,F,G,H, labels=c("E","F","G","H"), nrow=1, ncol=4, common.legend = FALSE)
g3<-ggarrange(I,J,K,L, labels=c("I","J","K","L"), nrow=1, ncol=4, common.legend = FALSE)
g4<-ggarrange(M,N,O,P, labels=c("M","N","O","P"), nrow=1, ncol=4, common.legend = FALSE)

g2

ggarrange(g1,g2,g3,g4, ncol = 1, nrow = 4)
ggsave("COI/Local_analysis/output/figures/NMDS_venn_cole_dip_vers1.png",height = 21, width = 20)



```

